### ISSUE TITLE
Need information on thresholds for all data layers

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#1]
Low/medium/high thresholds for hazards,  exposure and (even) for the risk are data package specific. E.g., "high" threshold for the heat in the data packages covering Napoli and Stockholm will not be the same. 

For exposure, it's not 100% sure if we really need this, but in principle it's the same.

For risk/impact, I'm not 100% sure if they will be in the data package or not but if they are (I think they should be), then again it's data package specific.

**Comment by p-a-s-c-a-l** [comment]
This issue should be addressed by the @clarity-h2020/science-support-team

**Comment by DenoBeno** [comment]
I have re-posted this in that forum and assigned this to astrid, to assure it isn't forgotten.

**Comment by p-a-s-c-a-l** [comment]
See https://github.com/clarity-h2020/data-package/issues/9, https://github.com/clarity-h2020/data-package/issues/8#issuecomment-444487538 and (https://github.com/clarity-h2020/data-package/issues/8#issuecomment-444863730)
