### ISSUE TITLE
1st Data Package: 04 Vulnerability Curves

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#15]
Vulnerability Data (Curves) needs to be included in the Data Package. ATM it is sufficient if we add some rich HTML description to the Vulnerability Curves Resource description that includes some static images of the curves.

This will then be shown under [Vulnerability Analysis/Data](https://csis.myclimateservice.eu/study/1/step/82/view/data). We will remove the tables tab from Vulnerability Analysis and later include a new data/diagram tab that dynamically renders the curves from data obtained via the [EMIKAT VA API](https://github.com/clarity-h2020/emikat/issues/13). In the long term we could also offer a component that allows the user to modify the curves. But for the beginning we can use static images of the curves.

IMHO @bernhardsk should be able to provide the required information for inclusion in the data package VA resource.

**Comment by p-a-s-c-a-l** [comment]
Possibility for defining vulnerability curves [is avialble](https://github.com/clarity-h2020/emikat/issues/16) and for [including them in data packages](https://github.com/clarity-h2020/emikat/issues/13#issuecomment-531298983), too. However, we still lack of the actual vulnerability functions.

**Comment by DenoBeno** [comment]
We could easily add vulnerability curves on the drupal side as attached file. We could also easily visualise them using chart suite (see https://github.com/clarity-h2020/csis/issues/98).

If we want to do this, I just need a table of values to show. And the chart suite module would not be bad.

Then EMIKAT would need to learn how to pick up this data and use it...

**Comment by p-a-s-c-a-l** [comment]
Available in Screening Data Package.
