### ISSUE TITLE
1st Data Package: 05  Risk & Impact (Heat Wave)

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#16]
Risk and Impact [Table](https://github.com/clarity-h2020/table-components/issues/4#issuecomment-466330518) and [Map](https://github.com/clarity-h2020/map-component/issues/30) data is currently not loaded from the Data Package, because there are no corresponding Resources in the Data Package. This is probably due to the fact, that Impact is calculated dynamically based on the study context (currently: study area, in the future additional: selected event, selected rcp, selected time period).

Example Impact result URIs:

- https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel1Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image/gif&cql_filter=HAZARD_EVENT='HW.6d_34C'
- https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2812/table/data

Therefore, dynamic and scenario (study) specific parameters like "view.2813" and "HW.6d_34C" must be configurable, that means replaced in the URI by parameters, e.g. $studyId as explained in https://github.com/clarity-h2020/data-package/issues/11#issuecomment-506661274 and $event Id.

**Comment by humerh** [comment]
The calculation of impacts (mortality) needs now a new data source:

As defined in the PLINIVS-Documentation "impact_calculation_mortality_v3.doc" (31.7.2019) we need for each city the number of deaths from heat waves.

Following data source is referenced:
_**-	Extract the number of deaths for each city related to 2012 (same year of Copernicus population dataset) from Eurostat (https://ec.europa.eu/eurostat/web/cities/data/database).**_ 

Where this database should be implemented?
- at Meteogrid server
- at Emikat server
- or anywhere alse???

**Comment by p-a-s-c-a-l** [comment]
I suggest in EMIKAT ... quickest solution.

**Comment by humerh** [comment]
Cities in Eurostat are defined as you find here:

https://ec.europa.eu/eurostat/documents/3859598/8012444/KS-GQ-17-006-EN-N.pdf/a3f1004f-cfae-4cc4-87da-81d588d67ae2,
Chapter 4;
https://ec.europa.eu/eurostat/documents/4313761/4311719/Metro_reg_Defining_urban_areas

Source of City records: https://ec.europa.eu/eurostat/documents/4422005/4430532/City-FUAs-Greater-cities-list-2017.xls


@maesbri, @patrickkaleta, @p-a-s-c-a-l 
We should have a link from our City-Definition to the definitions in EUROSTAT

**Comment by p-a-s-c-a-l** [comment]
Are you referring to our [Cities Taxonomy in CSIS](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/cities_regions/overview) that defines the cities/regions for which we have all the required UA LE Input layers for HC-LE and impact screening  calculation? Does it have to be extended?, e.g. mapped to Eurostat cities you mentioned above? 

FYI: This is how the cities taxonomy is created: https://github.com/clarity-h2020/docker-drupal/issues/68#issuecomment-523336896 The original data source is Urban atlas, right @therter ?

**Comment by humerh** [comment]
The needed statistic (Mortality/Population) for cities has been implemented in EMIKAT and is now available by:

https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/tab.CLY_EUROSTAT_CITIES.2056/table/data?rownum=1000

**Comment by therter** [comment]
> The original data source is Urban atlas, right @therter ?

I have the cities from the atos geoserver. See https://github.com/clarity-h2020/map-component/issues/24#issuecomment-497091003 . I think @negroscuro said that the cities came from urban atlas. But i am not sure. 

The cities from the atos geoserver have a field code. The values therein are similar to the UA_CODE_2017 field in https://ec.europa.eu/eurostat/documents/4313761/4311719/Metro_reg_Defining_urban_areas.  Wien has in geoserver the code "AT001L3" and in the eurostat excel file the value "AT001C1". I used the codes to assign the countries to the cities. It looks like all codes differ only in the last two characters

**Comment by humerh** [comment]
The exact definition is in https://ec.europa.eu/eurostat/documents/4313761/4311719/Metro_reg_Defining_urban_areas 
.
The coding used reflects the spatial hierarchy.

| Mask | Meaning |
| --- | --- |
| CC | Country_ Code |
| CCxxxLa |   Functional Urban Area (FUA) |
| CCxxxKb  |  Greater City |
| CCxxxCc   | City |
| CCxxxDzz  | Sub-city districts level 1 |
| CCxxxDzzyyy | Sub-city districts level 2 |

- xxx is a running number (since some cities were dropped or taken over from the former 'Large City Audit(6)
' list there are 'holes' in the numbering)

- The same running number (xxx) indicates that the City is included in the FUA (or in the Greater

City). However a FUA can include multiple Cities so not all Cities within a FUA will have the
same running number. The same applies to Greater Cities.

- Not all Cities have a FUA.

- a, b and c are version numbers reflecting the changes in the city boundaries.

**Comment by p-a-s-c-a-l** [comment]
OK, and who shall do what with this information? :-)

**Comment by p-a-s-c-a-l** [comment]
- The respective **Heat Hazard Impact on Population** Resource is described [here](https://github.com/clarity-h2020/data-package/issues/47)
- **Flood Hazard on Infrastructure** Impact still pending

**Comment by DenoBeno** [comment]
Make a new issue for flood hazards?

**Comment by p-a-s-c-a-l** [comment]
Description of the [Heat mortality risk/impact screening ](https://csis.myclimateservice.eu/node/1356) has to be updated. At the moment, it just contains *"This data is generated by EMIKAT **on the fly** and for the study area indicated by $emikat_id"* which is not enough.

We have to clearly describe the underlying methodology / models that lead to those results (mortality rate), the datasets that were used as input how these datasets  were produced, processed and derived (provenance) as well as any uncertainties and quality issues involved. This applies also to the respective Data Package Resources representing these input datasets which include population exposure managed in EMIKAT, HC-LE input layers, HC-LE output (TMRT), etc.

**Comment by p-a-s-c-a-l** [comment]
Remaining issues related to resource descriptions to be resolved here: https://github.com/clarity-h2020/csis/issues/140#issuecomment-588273362

**Comment by p-a-s-c-a-l** [comment]
Remaining issues related to resource descriptions to be resolved here: https://github.com/clarity-h2020/csis/issues/140#issuecomment-588273362
