### ISSUE TITLE
1st Data Package: 06 Adaptation Scenarios

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#17]
Add Resources for Adaptation Scenarios to the Data Package. Exact structure and appearance not yet clear. We need a modifiable adaptation options layers ([available here](https://github.com/clarity-h2020/emikat/issues/8)) but probably also a [RA/IA](https://github.com/clarity-h2020/data-package/issues/16) layer pointing to the **adapted** Baseline Scenario.

The [list of Adaptation Options](https://csis.myclimateservice.eu/adaptation-options-overview) in CSIS is also a resource that should be added to the data package. Furtermore, only the adaptation options that apply to the supported scenarios (e.g. heat wave impact on population) should become part of the data package. @maesbri How could we model this?

**Comment by p-a-s-c-a-l** [comment]
See also https://github.com/clarity-h2020/data-package/issues/44

**Comment by DenoBeno** [comment]
We had a discussion on this before and decided to add adaptation options to a data package as a separate data from resources. This is already implemented.
