### ISSUE TITLE
Update 1st Data Package Resources

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#18]
Update 1st Data Package Resources after specification update. Add
- [x] [tags](https://github.com/clarity-h2020/data-package/issues/14) and
- [x] [references](https://github.com/clarity-h2020/csis/issues/58) 

to resources and remove MapView and EU-GL Context entities.

See also https://github.com/clarity-h2020/docker-drupal/issues/76

**Comment by RobAndGo** [comment]
I'm not sure if this belongs here, but here is the data package json file for the **summer days** hazard characterisation index on the **European level**. I had to include the suffix .txt in order that github allowed me to upload the file.

[data_package_heat_indices_summer_days.json.txt](https://github.com/clarity-h2020/data-package/files/3346022/data_package_heat_indices_summer_days.json.txt)

Each resource within the data package gives the:
   a) model ensemble mean (odd numbered resources)
   b) model standard deviation (even numbered resources)
for each of the periods:
   1) baseline period (1971-2000)
   2) rcp26 (2011-2040, 2041-2070, 2071-2100)
   3) rcp45 (2011-2040, 2041-2070, 2071-2100)
   4) rcp85 (2011-2040, 2041-2070, 2071-2100)

That is, there are a total of 20 resources within this data package.

I have uploaded the corresponding data here:
/clarityftp/europe/hazard_indices/heat/summerdays/

**Comment by p-a-s-c-a-l** [comment]
What is the status here? E.g. in [Hazard Characterisation](https://csis.myclimateservice.eu/study/1/step/2/view/data), there are no resources shown:

![grafik](https://user-images.githubusercontent.com/1788226/60889310-0b7c5f00-a259-11e9-8f75-d1435a5b7219.png)


According to @fgeyer16, [Data Package Views](https://github.com/clarity-h2020/docker-drupal/issues/75) have been updated to use the tags. Maybe @DanielRodera could have a look why no Resources are shown? Please check also all other EU-GL Steps.

**Comment by maesbri** [comment]
> What is the status here? E.g. in [Hazard Characterisation](https://csis.myclimateservice.eu/study/1/step/2/view/data), there are no resources shown:

There are several in the naples data-package:
![image](https://user-images.githubusercontent.com/9677881/60987939-ee23bf80-a342-11e9-9b3b-259449181270.png)

Maybe it is related to the change that @patrickkaleta made in the "tags" list: https://github.com/clarity-h2020/docker-drupal/issues/78#issuecomment-510135152

**Comment by patrickkaleta** [comment]
> Maybe it is related to the change that @patrickkaleta made in the "tags" list: [clarity-h2020/docker-drupal#78 (comment)](https://github.com/clarity-h2020/docker-drupal/issues/78#issuecomment-510135152)

No, I doubt there's a relation. I only changed the way the items in the tags list are shown. I didn't change the structure of that field, nor did I change the view @fgeyer16 created to display the resources.

My guess is that there's something wrong with the view. Just checked it and it seems that it still uses some deprecated features like the dp_eu_gl content type:
![eva-tags-view](https://user-images.githubusercontent.com/42167036/61031367-adb65700-a3bf-11e9-8c55-d5dd67e6c497.png)

@fgeyer16 can you please have a look at your [view ](https://csis.myclimateservice.eu/admin/structure/views/view/step_data_collection/edit/entity_view_2) again and remove everything that we don't want to use anymore (like e.g. the `dp_eu_gl` entity type)

**Comment by maesbri** [comment]
> No, I doubt there's a relation. I only changed the way the items in the tags list are shown. I didn't change the structure of that field, nor did I change the view @fgeyer16 created to display the resources.

ok, sorry for the confusion. Maybe it is time to start removing all outdated stuff in order to avoid similar problems

**Comment by maesbri** [comment]
@DenoBeno , @patrickkaleta Have you changed anything related to edition permissions? I was about to start updating the Naples data package resources but I cannot save anymore the changes. Now, only the Preview button is shown (at the bottom of the form).

![image](https://user-images.githubusercontent.com/9677881/61219858-627cab00-a715-11e9-89d0-24d82daedb7a.png)

**Comment by patrickkaleta** [comment]
> @DenoBeno , @patrickkaleta Have you changed anything related to edition permissions? I was about to start updating the Naples data package resources but I cannot save anymore the changes. Now, only the Preview button is shown (at the bottom of the form).
> 
> ![image](https://user-images.githubusercontent.com/9677881/61219858-627cab00-a715-11e9-89d0-24d82daedb7a.png)

Permissions have not been changed, but I can reproduce the same behaviour. I will have a look at this.

**Comment by patrickkaleta** [comment]
> @DenoBeno , @patrickkaleta Have you changed anything related to edition permissions? I was about to start updating the Naples data package resources but I cannot save anymore the changes. Now, only the Preview button is shown (at the bottom of the form).

Accidentally the "Preview before submitting" option has been set to "required". This caused the missing Save button. I fixed that for both content types.

**Comment by maesbri** [comment]
> Accidentally the "Preview before submitting" option has been set to "required". This caused the missing Save button. I fixed that for both content types.

ok, my fault then. I had done it assuming that it meant making the "title" property mandatory (as it is done with the other fields we defined) :(

**Comment by fgeyer16** [comment]
> What is the status here? E.g. in Hazard Characterisation, there are no resources shown

On changing to Tags the view which created did not work properly. I recreated the view. Now everything should be shown again.

**Comment by DenoBeno** [comment]
I am looking at the [European Wide Data package](https://csis.myclimateservice.eu/node/682).

* It has several hazard indices (all heat) defined. I suppose we are still waiting for the flooding data?
* Also several local effect parameters
* No local hazard layers
* One exposure layer (population, shouldn't we also have buildings?)
* one "adaptation" resource? Not sure what this is.
![image](https://user-images.githubusercontent.com/2961790/62376219-74958080-b540-11e9-8330-0bad758f097d.png)

Questions: 

1. I don't know if what is in there now is up to date, who can check this?
2. What is missing now?
3. Who is responsible for adding flooding data?

**Comment by p-a-s-c-a-l** [comment]
tags & references updated
