### ISSUE TITLE
Make available new HC Layers via WMS

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#19]
There are new Hazard indexes [available](https://github.com/clarity-h2020/data-package/issues/4#issuecomment-507289003) that should be via [METEOGRID Geoserver](https://clarity.meteogrid.com/geoserver/web/) WMS and proper styling should be added. The respective [HC Resources](https://github.com/clarity-h2020/data-package/issues/8) have to be added to the Data Package so that the new layers can be recognized by the [HC Map Component](https://github.com/clarity-h2020/map-component/issues/33).

Note : Those Layers are just informative and not used for impact calculation in EIMKAT. EMIKAT uses the [Hazard Events Layers](https://github.com/clarity-h2020/csis/issues/57). Therefore this issue is currently put on hold until the most pressing tasks have been completed.

**Comment by ghilbrae** [comment]
@RobAndGo I've tested a couple of the new layers and I'm having trouble uploading them to geoserver, the error may be related to the projection, though I'm not 100% certain. The older layers do not seem to have this problem.

```
Could not list layers for this store, an error occurred retrieving them: 
Failed to create reader from file:data/hazard/summerdays/SummerDays_historical_19710101-20001231_ensstd.tiff
and hints Hints: EXECUTOR_SERVICE = java.util.concurrent.ThreadPoolExecutor@551703ad[Running, pool size = 0, active threads = 0, 
queued tasks = 0, completed tasks = 0] REPOSITORY = org.geoserver.catalog.CatalogRepository@459616d8
System defaults: FILTER_FACTORY = FilterFactoryImpl COMPARISON_TOLERANCE = 1.0E-8 
FORCE_LONGITUDE_FIRST_AXIS_ORDER = true FEATURE_FACTORY = org.geotools.feature.LenientFeatureFactoryImpl@38e3daf6 LENIENT_DATUM_SHIFT = true 
GRID_COVERAGE_FACTORY = GridCoverageFactory TILE_ENCODING = null 
FORCE_AXIS_ORDER_HONORING = http STYLE_FACTORY = StyleFactoryImpl
```
When I use gdalinfo on the file there is no projection data and there's also no .prj file that can be used. Do you have these files for these layers?

**Comment by RobAndGo** [comment]
Hmmm, I think last time I may have uploaded the original netcdf files to @luis-meteogrid and he converted them into geotiff files. I'll see if I can corrected the error with the geotiff files myself.

@luis-meteogrid : What command did you use to convert the netcdf to geotiff? I am using gdal_translate.

**Comment by ghilbrae** [comment]
Thank you! If it takes too much time just leave it on hold, this task in not urgent, as stated by Pascal.

**Comment by ghilbrae** [comment]
@RobAndGo I've checked with my colleagues and they think it's better if you just send us the netcdf files, for them is very simple and straightforward to get the rasters with all the information needed.

But, as I said, this is not a priority.

**Comment by RobAndGo** [comment]
Thank you!! That saves me a lot of work! :-)
I have put the files under the subdirectory netcdf in the following directories:
/clarityftp/europe/hazard_indices/heat/hotdays/
/clarityftp/europe/hazard_indices/heat/summderdays/
/clarityftp/europe/hazard_indices/heat/tropicalnights/

**Comment by ghilbrae** [comment]
@RobAndGo there are a bunch of these layers for tropical nights already available on our geoserver: https://clarity.meteogrid.com/geoserver

If you see something wrong, let us know. Also, let us know if the scale is off.

**Comment by ghilbrae** [comment]
And all layers (Summer Days, Hot Days and Tropical Nights) are available now.

**Comment by ghilbrae** [comment]
@RobAndGo I've been working with the hydrology layers that were uploaded to the FTP a couple of weeks ago and I have noticed a couple of things that I don't know if are as intended. I think you mentioned these layers had been created by someone else, so feel free to tag them in this issue so they may give us a better insight in the matter.

Each of the netcdf files contains six bands that are simply named as value1, value2, ..., value6, is this as intended? It should be no problem but it will take a bit longer to process.

I've tested one of the files (cout-yearmax_returnPeriod100_ref_EUR-44_rcp26_IMPACT2C_QM-EOBS_1971-2000_remap0.5.nc) and picked three of the bands (just to ensure that everything worked fine). You can see the result here: https://clarity.meteogrid.com/geoserver/europe/wms?service=WMS&version=1.1.0&request=GetMap&layers=europe%3Aoutput&bbox=-25.0%2C33.0%2C40.0%2C72.0&width=768&height=460&srs=EPSG%3A3035&format=application/openlayers#toggle

Let me know if it looks ok so I can start processing all these layers.

Thanks!

**Comment by RobAndGo** [comment]
This appears to show river flood information, but I'm not sure what the values/colours mean. This data has been produced from SMHI - perhaps @LenaStr would have more information. Is Yeshewa or Jorge Amorim on github?

**Comment by DenoBeno** [comment]
What is the status here?

**Comment by RobAndGo** [comment]
@LenaStr Could you check the hydrology data which was prepared by @ghilbrae in the following [post](https://github.com/clarity-h2020/data-package/issues/19#issuecomment-516398550).

**Comment by p-a-s-c-a-l** [comment]
Can be closed?

**Comment by RobAndGo** [comment]
Yes, I think so as what I posted [here](https://github.com/clarity-h2020/data-package/issues/41#issuecomment-547833602) would also apply to this issue.
