### ISSUE TITLE
How will the system know where to show the resources?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#24]
In the "Simple Data Package" the resource can in principle be taged by eu_gl step terms, but the wiki doesn't instruct people to do so. How will the site know where to show the resource?

**Comment by maesbri** [comment]
I presume you had a look at the wiki some hours ago (it was not yet finished)... I've been working on that during the afternoon showing how to describe a hazard index resource.

Tagging the resource is mandatory, otherwise, as you said, the system doesn't know where to show/use the resource.

**Comment by patrickkaleta** [comment]
Out-of-the-box our options for validating the selected values in that field are limited. We can make it a "required" field and set the number of allowed values. And that's it - so we would have to rely on the editors to always select tags from certain categories (like the EU-GL step).
Or maybe we could add a [custom validation](https://www.drupal.org/docs/8/api/entity-api/entity-validation-api/providing-a-custom-validation-constraint) to the tags field, which would check if certain tags are set or not. 
Constraints could look like this: 
- the selection must contain at least one term from EU-GL taxonomy
- it must contain exactly one term from DP_ResourceType and one term from DP_ServiceType taxnomomies
- ...

I don't believe that the [Field Validation module](https://www.drupal.org/project/field_validation) would be an alternative, since I don't see it offering a function to check if a field contains values from several, certain taxonomies.

**Comment by p-a-s-c-a-l** [comment]
> And that's it - so we would have to rely on the editors to always select tags from certain categories (like the EU-GL step).

That's enough. IMHO we can expect from partners that have been working for more than 2 years in this project to associate the resource with the correct EU-GL Step. ;-)

On the other hand, we have to validate the Data Packages anyway before presenting them on our platform (quality control). Therefore 'published' could be set to `false`by default.

**Comment by DenoBeno** [comment]
Making the tags compulsory and adding a help text that explains what needs
to be done is a good start.

Maybe we should also move the tags nearer to the top of the form to give
them more visibility.

If anyone has a better idea for a name, we could also rename Tags to
something more appropriate. Maybe Categories or Categorisation?

As for the custom validation, that sounds like a good idea, but I'm not
sure how much work would it be. Maybe the business rules could do the same?

**Comment by DenoBeno** [comment]
I just took a closer look at the "Tags", renamed them in the "Categorization" and pushed them towards the top of the form, However, I am confused as to what should be tagged.

1) EU_GL step and resource type appear to be somewhat redundant. Do we really need both?
2) each hazard indice has a hazard type, no? Why does the user need to choose both?
3) same for elements at risk and damage classes.

Every time that the user has to choose two dependent variables but they can choose them independently, we will have an error source at hand.

"Service type" is the most confusing of all for me. If I understand it correctly, each resource can have more than one presentation. These presentations can be defined using the "path" and using the "path" variable and each path is pointing to a specific service type. What we do now could result in five tags and five paths with no obvious correlation between the two. Why aren't we tagging each path separately with the service type? And how is this used downstream? Does every map widget search through all defined paths until it finds one (or more?) that points to WMS? How does it recognize the service type?

**In fact, I'm not sure if I understand the concept of resource. Can one resource belong to more than one GL_step? Can it contain data for more than one hazard? More than one hazard indice?**

**Comment by DenoBeno** [comment]
Btw., how to assure that only hazards or only hazard indices are shown in the next field when "hazards" GP_step is chosen is explained here 

https://www.drupal.org/docs/8/modules/business-rules/advanced-usage/dependent-field

I suppose this is already used with country/city selection in studies.

**Comment by patrickkaleta** [comment]
> Btw., how to assure that only hazards or only hazard indices are shown in the next field when "hazards" GP_step is chosen is explained here
> 
> https://www.drupal.org/docs/8/modules/business-rules/advanced-usage/dependent-field
> 
> I suppose this is already used with country/city selection in studies.

@DenoBeno 
We configured the Tags (or "Categorization" as you renamed it) as an Entity Browser. In the description link you posted it's written that the fields **need to be rendered as "Select lists" or "Checkboxes" in order for it to work**. 
Also, we couldn't store all of it in a general `Tags` field as we do now, but instead would have to use separate fields: `Tags-Hazards`, `Tags-Hazard indexes`, `Tags-Elemetn at risk`,...
And on top of that we would need to cross-reference all involved taxonomies for this to work.

I think what we have right now (the help text directly in the form, the detailed step-by-step tutorial created by @maesbri ) should be good enough to present it to users.

**Comment by DenoBeno** [comment]
Guess this can be put on hold for now.

**Comment by DenoBeno** [comment]
I'm closing this, it doesn't seem to have much importance. If we ever decide to do something about it, we can re-open it or open a new one.
