### ISSUE TITLE
Adding tags different in data packages and in the resources

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#25]
Why don't we use the same (or a similar?) entity browser for adding tags in the data package as we use in the dp_resource?

**Comment by patrickkaleta** [comment]
> Why don't we use the same (or a similar?) entity browser for adding tags in the data package as we use in the dp_resource?

We could do that but since we don't have any kind of hierarchy or grouping in the data package keywords (as it's the case for the resource tags), I don't think it's necessary to apply a more sophisticated display of that field.

**Comment by RobAndGo** [comment]
@DenoBeno worked through each step of the EU-GL and I wrote down his ideas/suggestions regarding the tags in the data package here:
[eugl_tags_hierarchy.txt](https://github.com/clarity-h2020/data-package/files/3416822/eugl_tags_hierarchy.txt)
Here the file in full (I hope it's self-explanatory):
```
What tags are shown when a user chooses:

Hazard characterisation:
– 1 hazard 
– 1 hazard index (maybe more than 1?)
- 0 elements at risk
- 0 damage classes
- 0 vulerability classes
– 1 emissions scenario
- 0 impact scenarios
- 1 resource type: hazard-index
– 1 service type (path) [all of the same service type]

Hazard characterisation local effect (Version 1: input layer data - elements at risk?):
– 0 hazard 
– 0 hazard index 
- 1 (or more?) elements at risk (input layers could be elements at risk as well?)
- 0 damage classes
- 0 vulerability classes
– 0 emissions scenario
- 0 impact scenarios
- 1 resource type: local-effects-parameter
– 1 service type (default path) [all of the same service type]
We potentially have a lot of data here - do we want to add each one as a resource? Or an alternative solution?
How does the system know which input layers it is dealing with?

Hazard characterisation local effect: (Version 2: perhaps belongs to Impact Assessment below?)
– 1 hazard 
– 1 hazard index (maybe more than 1?)
- 0 elements at risk
- 0 damage classes
- 0 vulerability classes
– 1 emissions scenario
- 1 impact scenarios
- 2 resource types: hazard-index, hazard-event
– 1 service type (default path) [all of the same service type]

Exposure:
– 0 hazard 
– 0 hazard index 
- 1 elements at risk
- 0 damage classes
- 1 (or more?) vulerability classes - when selecting elements at risk, only the relevant classes are shown.
– 0 emissions scenario
- 0 impact scenarios 
- 1 future development scenario (should be available?)
- 1 resource type: element at risk (not currently defined)
– 1 service type (default path) [all of the same service type]

Vulnerability:
– 1 (or more) hazard 
– 1 (or more) hazard index 
- 1 (or more) elements at risk
- 1 (or more) damage classes
- 1 (or more) vulerability classes
– 0 emissions scenario
- 0 impact scenarios (ideally future development scenario)
- 1 resource types (damage-level-probability-function) - need to connect the vulnerability class to hazard. Vulnerability classes are currently only connected to elements of exposure.
– 1 service type (default path) [all of the same service type]
Potentially a large number of functions each of which connect one hazard and one element at risk to one (or more) damage classes. 
Q. Are each of these functions one resource, or group them all into one resources (more practical).
There can be vulnerability curve for the number of people who are sick, the number of lost days of work, etc. e.g. multiple vulnerability curves for the one hazard and one element at risk. How to handle such a case?

Risk and Impact Assessment:
– 0(1?) hazard 
– 0(1?) hazard index
- 0(1?) elements at risk
- 0(1?) damage classes
- 0(1?) vulerability class
– 1 emissions scenario 
- 1 impact scenarios (ideally future development scenario)
- 1 future development scenario (should be available?)
- 1 resource type: "risk indicator" (not currently defined)
– 1 service type (default path) [all of the same service type]
For the screening data package, we only see the possibility to put local hazard data here. For the expert data package, we could have results of the risk and impact assessment analysis (some indicators).

Adaptation Options: Identification:
– 1 (or more) hazard 
– 0 hazard index 
- 1 (or more) elements at risk
- 0 damage classes
- 0 vulerability classes
– 0 emissions scenario
- 0 impact scenarios (ideally future development scenario)
- 1 resource type: adaptation_options
– 0 service type (default path) [all of the same service type]
There could be many adaptation options. Do we have each option as a separate resouce, or group them all into one resource?

Adaptation Options: Appraisal:
– 1 hazard 
– 0 hazard index 
- 1 elements at risk
- 0 damage classes
- 0 vulerability classes 
– 0 emissions scenario
- 0 impact scenarios (ideally future development scenario)
- 1 resource type: adaptation_options
– 1 service type (default path) [all of the same service type]
Applies for the expert data package. For the screening only an indicator to show how expensive the options are, is already part of the "AO Identification" above.

Adaptation Action Plans: Implementation:
– 1 (or more) hazard 
– 0 hazard index 
- 1 (or more) elements at risk
- 0 damage classes
- 0 vulerability classes
– 1 (or more) emissions scenario
- 1 (or more) impact scenarios (ideally future development scenario)
- 1 resource type: adaptation_options ("adaptation option action plan" should be defined?)
– 1 service type (default path) [all of the same service type]
Examples of implementation - doesn't belong to screening but to showcases. Showcases exist independent of data packages.
Within the expert study, a detailed description can be provided as an e.g. pdf text.

```

**Comment by DenoBeno** [comment]
I defined a simple entity browser for adding adaptation options to the data package (so that we don't have to define them as dp_resource. 

Issues:

1. Hazard selection should only show the tags we use (forgot how to do this)
2. User can select duplicates
3. Duplicates shown in the list (needs fixing)
4. Selecting "all" would be very difficult. Maybe we can treat "none selected" as "select all" in the view later?
5. If I select to only show title ("label") in the preview, nothing is shown.
6.

**Comment by DenoBeno** [comment]
I tried to fix the number 1 "Hazard selection should only show the tags we use (forgot how to do this)" but this is more difficult than expected. 

For the start, the problem is in design of our taxonomies: 

- hazards taxonomy has several levels and also contains the hazard indices. 
- Elements at risk is even worde, as it contains damage classes and vulnerability classes
 
![grafik](https://user-images.githubusercontent.com/2961790/61810215-0b768480-ae3f-11e9-83cc-1fba1fc92625.png)

This should have been three separated taxonomies, just as countries and cities are separated taxonomies with cities explicitly linking to countries through an entity reference. 

Now, I know how unhappy you are whenever I mention that something should be redesigned, so I thried to look for a workaround. 

In defining the tags, the workaround was to use the entity queues listing only the terms we want to show to the user. However this doesn't work in the views.
One possibility would be to show only the terms for which content exists. There is even a modeule doing this, but only on github (D8 version): https://github.com/bmcclure/drupal-views_selective_filters . The issue with this approach is that it fires a DB query over all nodes of a type used in the view every time a list is built, so it could be slow.
What *should* work in views is what I tried out in https://csis.myclimateservice.eu/testpage . Unfortunately, it doesn't work and I don't understand why. This is how it's supposed to work:

1) I defined a "relevant hazards" taxonomy and linked some terms from hazard taxonomy to the same terms from this taxonomy. (just "heat" for now)
2) I added a relation to adaptation options effects and then to "involved hazards" terms 
3) this makes it possible to filter on terms from "relevant hazards", which _should_ in turn choose correct "involved hazard" terms, then the right addaptation options effect and finally the correct adaptation options.

Unfortunately, this doesn't work at all.

@fgeyer16, do you have any idea how to make this work?

**Comment by patrickkaleta** [comment]
> I defined a simple entity browser for adding adaptation options to the data package (so that we don't have to define them as dp_resource.
> 
> Issues:
> 
> 1. Hazard selection should only show the tags we use (forgot how to do this)

Seeing that this cannot be achieved in a simple manner, I would just drop that idea because it's a **nice-to-have feature but not essential**.

Two additional reasons:
- after a while (hopefully) we will have numerous adaptation options covering all available hazards --> then this functionality wouldn't be needed at all
- showing to the users only hazards for which we have adaptation options might let them to believe that our platform simply doesn't cover any other hazards, when the true problem is that we just don't have the appropriate adaptation options yet --> IMO this message should be rather displayed to the user instead of just hiding the "unused" hazards

**Comment by patrickkaleta** [comment]
> I defined a simple entity browser for adding adaptation options to the data package (so that we don't have to define them as dp_resource.
> 
> Issues:
> 2. User can select duplicates
> 3. Duplicates shown in the list (needs fixing)
> 4. Selecting "all" would be very difficult. Maybe we can treat "none selected" as "select all" in the view later?

I stumbled upon the [Entity Browser Enhanced](https://www.drupal.org/project/entity_browser_enhanced) module, which might be able to fix some of the above mentioned issues. I will check it out and report back.

**Update:**
I tested the mentioned module and it is not offering what we are looking for.

**Comment by patrickkaleta** [comment]
> I defined a simple entity browser for adding adaptation options to the data package (so that we don't have to define them as dp_resource.
> 
> Issues:
> 5. If I select to only show title ("label") in the preview, nothing is shown.

That's an issue with the CSS styling. It is showing white text on white background. This should be fixed once the new theme is deployed.

**Comment by patrickkaleta** [comment]
> What _should_ work in views is what I tried out in https://csis.myclimateservice.eu/testpage . Unfortunately, it doesn't work and I don't understand why. This is how it's supposed to work:
> 
> 1. I defined a "relevant hazards" taxonomy and linked some terms from hazard taxonomy to the same terms from this taxonomy. (just "heat" for now)
> 2. I added a relation to adaptation options effects and then to "involved hazards" terms
> 3. this makes it possible to filter on terms from "relevant hazards", which _should_ in turn choose correct "involved hazard" terms, then the right addaptation options effect and finally the correct adaptation options.
> 
> Unfortunately, this doesn't work at all.
> 
> @fgeyer16, do you have any idea how to make this work?

I believe the problem is described [here](https://www.drupal.org/project/drupal/issues/571548). Views create identifiers based on the machine names of the entities and fields, which can get pretty long. However, Postgres only uses identifiers with max. 63 characters.

**Comment by DenoBeno** [comment]
Indeed, the problem was in the long variable names. I'll add a few new issues explaining the proposed "best practices" for CSIS design based on what I have learned here.

**Comment by fgeyer16** [comment]
I lost somehow the track. Datapackage related stuff seems to change faster than I am able to understand it.This is about how to persuade/guide the user to give the resource the right tags dependent on specific tags?

It would be easier if we go back to separate fields for the different things, because then they can be made dependend from each other mode easily. Business rules is our friend.

Anyway on my point of view  the barrier that a resource is created easily is not that we have one or hundred fields to fill but that the resource has to be categorized by so many parameters, which are dependend from each other as well. I think this will always scary users to fill the form. 
What about another approach? Let us offer links/buttons to the user which will create a resource prefilled with the proper categorization?
For 

> Hazard characterisation:
– 1 hazard 
– 1 hazard index (maybe more than 1?)
– 0 elements at risk
– 0 damage classes
– 0 vulerability classes
– 1 emissions scenario
– 0 impact scenarios
– 1 resource type: hazard-index
– 1 service type (path) [all of the same service type]

we can create links following the scheme  

> add hazard-index for {{hazard/hazard index}} {{emission scenario}}

and create a node through this with the tags for hazard, hazard index, GL-Step, resource type and emission scenario prefilled. The user will then only have to fill out the service type (or we create links for each service type)

I'm aware that we will create a lot of links this way which we will have to present in a clear way. I think about something like here https://csis.myclimateservice.eu/study/1/step/2/view/data. But I think a big link list is less scary than a long list of options...

**Comment by p-a-s-c-a-l** [comment]
> I lost somehow the track. Datapackage related stuff seems to change faster than I am able to understand it

Agreed. IMHO it's good enough  as it is. Let's see if users can work with it then we still improve later if needed. There are currently **[more pressing issues](https://github.com/orgs/clarity-h2020/projects/2)** than making the tag selection as easy as possible. 

> It would be easier if we go back to separate fields for the different things, because then they can be made dependend from each other mode easily.

This means changing our components again, therefore not an option atm. Let's keep it simple and try to move forward.

**Comment by DenoBeno** [comment]
OK, this will stay as is - at least for now. Closing.
