### ISSUE TITLE
Why do we need the default path?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#27]
In DP resources, we currently have the "default path" (==path) and the "alternative paths" (==references). The way I see it, the default path is not needed and only complicates things. 

Can't we just get rid of it and declare the first reference to always be a default path? This would be IMO easier both the users and for the application developers.

FYI: I noticed this because I wanted to make a list of all service calls from resources - as this is defined now, I have to separately catch the default path and the additional references.

**Comment by p-a-s-c-a-l** [comment]
The DP Data model is the result of a long and thorough specification process. Therefore I wouldn't just arbitrarily remove properties from the data model. This path property e.g. is used in the table component. If we remove it, it breaks the component (again). 

Once our users are actually using the system, we can implement improvements based on **their feedback**. ATM we should IMHO stop guessing what they *might* want or not. We have to offer *something* usable, then we'll see how to improve.

**Comment by DenoBeno** [comment]
This is not a question of (just) user experience, it's a question of a bad design. You say that the table component uses path, but how can the table component use this if path is e.g. pointing to a map server? 

Here is a list of all default paths (==path or uri variable): https://csis.myclimateservice.eu/maintenance/resources/paths
Here is a list of all "alternative paths" (=references)
https://csis.myclimateservice.eu/maintenance/resources/paths2

What I *could* do if we really want to keep this field for a while longer is the following:

1) define a rule that will fill the value of default path (path) by using the first of the alternative paths (references)
2) also add this automatically to tags.

**Comment by p-a-s-c-a-l** [comment]
> This is not a question of (just) user experience, it's a question of a bad design. You say that the table component uses path, but how can the table component use this if path is e.g. pointing to a map server?
> 
> Here is a list of all default paths (==path or uri variable): https://csis.myclimateservice.eu/maintenance/resources/paths
> Here is a list of all "alternative paths" (=references)
> https://csis.myclimateservice.eu/maintenance/resources/paths2
> 
> What I _could_ do if we really want to keep this field for a while longer is the following:
> 
>     1. define a rule that will fill the value of default path (path) by using the first of the alternative paths (references)

I wouldn't mess with that now. Path is part of the specification. Who defines what is the *first* reference? Is the order always guaranteed to be be same, also when querying the API.  @maesbri What's your opinion?

> 
>     2. also add this automatically to tags.

huh?

**Comment by maesbri** [comment]
> > This is not a question of (just) user experience, it's a question of a bad design. You say that the table component uses path, but how can the table component use this if path is e.g. pointing to a map server?
> > Here is a list of all default paths (==path or uri variable): https://csis.myclimateservice.eu/maintenance/resources/paths
> > Here is a list of all "alternative paths" (=references)
> > https://csis.myclimateservice.eu/maintenance/resources/paths2
> > What I _could_ do if we really want to keep this field for a while longer is the following:
> > ```
> > 1. define a rule that will fill the value of default path (path) by using the first of the alternative paths (references)
> > ```
> 
> I wouldn't mess with that now. Path is part of the specification. Who defines what is the _first_ reference? Is the order always guaranteed to be be same, also when querying the API. @maesbri What's your opinion?
> 
> > ```
> > 2. also add this automatically to tags.
> > ```
> 
> huh?

@DenoBeno , I think you are misusing the original purpose of the Data Package specification as I defined it.
resource.path is a pointer to the data. According to the general specfication, It doesn't matter which kind of pointer (to an file in a http server, ftp, a request to a wms, wfs, etc.).
However, since in CLARITY we faced the "problem" of defining the a resource with path pointing to the "raw" data (e.g., a wfs request) and at the same time we wanted to be able to visualize the data in the form of a map (wms request) we introduced the resource.references property, which allowed, among other things, to add "alternative" references to the data (in this case to a wms request). This was the solution for not having to define a new resource with the wms request.
This is represented in the following manner: 
"references":  [ {"type": "mapview:ogc:wms", "qualifier": "#/path", "path": "htttp://wms-request"}]

The "qualifier" property value "#path" is just used to indicate that the wms url refers to the resource.path url.

The idea behind the qualifier is not just limited to this example, there are other potential uses, like:
["@mapview:ogc:wms", "damage-class:population:d1", "https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel1Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image/gif&cql_filter=HAZARD_EVENT='HW.6d_28C'"],
    ["@mapview:ogc:wms", "damage-class:population:d2", "https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel2Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image/gif&cql_filter=HAZARD_EVENT='HW.6d_28C'"],
    ["@mapview:ogc:wms", "damage-class:population:d3", "https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel3Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image/gif&cql_filter=HAZARD_EVENT='HW.6d_28C'"],
    ["@mapview:ogc:wms", "damage-class:population:d4", "https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel4Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image/gif&cql_filter=HAZARD_EVENT='HW.6d_28C'"],
    ["@mapview:ogc:wms", "damage-class:population:d5", "https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel5Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image/gif&cql_filter=HAZARD_EVENT='HW.6d_28C'"]

Here we are indicating that the information related to tag "damage-class:population:d1" is available via the corresponding wms request and so on.

Order of the references should be unimportant, since it is up to de CSIS to decide what to do in each case with the reference information (type=@mapview:ogc:wms, qualifier and path)

**Comment by DenoBeno** [comment]
@maesbri: I believe you that this may not be in line with original resource definition. The problem is that *now*  we have two fields containing de-facto the same information, but in a slightly different way.

- for "default path" - a single tag indicating the service type + path or possibly several paths.
- for "other paths" (references) - zero to * lines containing a *different* service type tag, the "qualifier" and a path.

Default path can be anything (e.g. wms, wcs, other) and so can other paths. This means that any widget that we produce must look through default and all "other" paths in order to find whatever it is responsible for visualizing, e.g. map layers or table data. And the service tags are different for the two cases. And the qualifier only exists in references. 

If you folks really want to keep it that way, fine but IMO this will make all developments unnecessary difficult (==waste of time down the road)

**Comment by p-a-s-c-a-l** [comment]
ATM just the [Adaptation Options Table](https://github.com/clarity-h2020/table-components/issues/6) uses the path property to load an [external JSON file](https://github.com/clarity-h2020/data-package/blob/master/examples/dc1-naples/data/adaptation-options/adaptation-options.json). However, this component is now obsolete, as we manage the Adaptation Options within Drupal. Correct, @therter?

Therefore, in the future we'll just use the references property for out widgets.

**Comment by therter** [comment]
> ATM just the [Adaptation Options Table](https://github.com/clarity-h2020/table-components/issues/6) uses the path property to load an [external JSON file](https://github.com/clarity-h2020/data-package/blob/master/examples/dc1-naples/data/adaptation-options/adaptation-options.json). However, this component is now obsolete, as we manage the Adaptation Options within Drupal.

This is correct

**Comment by DenoBeno** [comment]
OK, I have implemented a minimal change to the dp_resource now, to assure we get the correct data:

1. First, I have changed the description for the "Default path" and renamed it into "Download path". (this doesn't change the variables, just the labels)
2. Second, I have made the references field obligatory and renamed it into "Service paths".
3. Third, we can actually drop the service type tag from the "tags". I haven't done this yet though.

This is the result:

![image](https://user-images.githubusercontent.com/2961790/62365745-2757e580-b525-11e9-97be-14fa8980a446.png)

![image](https://user-images.githubusercontent.com/2961790/62365794-4191c380-b525-11e9-888d-f6709ab2db62.png)

This is how "add new mode" looks like:

![image](https://user-images.githubusercontent.com/2961790/62365833-62f2af80-b525-11e9-8d5e-7b154d7cf0bf.png)

If title is not provided, one is generated automatically. However, the automatic titles are unreadable and thus I'm allowing the users to define some on their own now. E.g. for the emikat population resource:

![image](https://user-images.githubusercontent.com/2961790/62366152-663a6b00-b526-11e9-8b46-952b8d50e5c9.png)

I think that this is a good way to close this issue. WDYT?

**Comment by p-a-s-c-a-l** [comment]
> 3. Third, we can actually drop the service type tag from the "tags". I haven't done this yet though.

Hm' I wasn't aware that service type is also part of the tags. We don't the service type in both places, so which one is the correct one? 

According to [this comment](https://github.com/clarity-h2020/data-package/issues/14#issuecomment-505773944) from @maesbri, `field_resource_tags`is the right place for service type! That's also the reason why `field_service_type` is labelled **REMOVE__service_type**. 😕

**Comment by DenoBeno** [comment]
Indeed, there are two places for service tags - once in the "path" and once in the "references". And the one related to path is terribly designed because one can't define it per path.

Consequently, we are using the "references" for paths now. (Label: service paths)

As for the path itself, the label is "Download path(s)" now, and the instructions clearly state that our service will ignore whatever is in here. Consequently, we don't really care about the service type. I can leave the tag or remove it, in any case it shouldn't be used by our widgets.

For me, this means that we can close this issue.

The only remaining issue is that DIFFERENT tags are used in references - see this ticket: https://github.com/clarity-h2020/data-package/issues/34

**Comment by p-a-s-c-a-l** [comment]
> Consequently, we don't really care about the service type.

We do! See https://github.com/clarity-h2020/docker-drupal/issues/85#issuecomment-517638669

>  I can leave the tag or remove it, in any case it shouldn't be used by our widgets.

Service type **will** be used in our widgets. I expect it to be present in the tags array.

**Comment by DenoBeno** [comment]
I think you are wrong on this (we aren't using the service type tag, we are only using the service type field in resources), but anyway - it's good enough. I'm closing this.

**Comment by p-a-s-c-a-l** [comment]
> I think you are wrong on this (we aren't using the service type tag, we are only using the service type field in resources), but anyway - it's good enough. I'm closing this.

Please see https://github.com/clarity-h2020/data-package/issues/14#issuecomment-505773944

So that means the service type field in resources is obsolete. And that's exactly the reason why @maesbri prefixed the field name with **REMOVE**:

![grafik](https://user-images.githubusercontent.com/1788226/62376454-f38ab900-b540-11e9-9acc-c78da04f380d.png)

And therefore we already adapted our implementation [here](https://github.com/clarity-h2020/map-component/issues/28) and [there](https://github.com/clarity-h2020/table-components/issues/17) to use the common tags array instead of the dedicated fields like `field_service_type` or `field_map_view` which btw are all prefixed with REMOVE.
