### ISSUE TITLE
DP references weirdness

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#28]
I have just noticed something weird concerning the dp_reference data type:

1) The title is set by adding together the service type and the uri. 
2) It is currently not possible to reuse existing references again. If I enable this, the user has to search for the existing resource by the title.

As a consequence, we already have at least one duplicated reference defined (same title == same reference, just different nid. 

Now, I tried allowing the users to reuse the existing resources, but the automatic search function doesn't work as expected (see illustration)

I'll try with entity browser to see if the search works, but the real question is: 

should the titles stay as they are or should we allow the user to generate own titles? And should we add a check to assure the title is unique?

**Comment by p-a-s-c-a-l** [comment]
> Now, I tried allowing the users to reuse the existing resources, but the automatic search function doesn't work as expected (see illustration)

Which illustration?

Do you mean **references** or **resources**? That's a important point! Because references shouldn't be reused as they are bound to the resource. Changing a reference **shall not** have influence on any resource other than the resource containing the reference! There is absolutely no need for reusing references. Instead, resources can be reused in different Data Packages. 

Therefore I wouldn't put any effort on the title as the user will / shall never see it.

**Comment by DenoBeno** [comment]
A, so it's not an issue if references are duplicated?  This should have been defined as paragraf then, but I kind of understand the reasoning.

**However, there is another weird thing with types of references.** 

- In references, the reference type is defined differently than in the tags for the default path (url) in the resources. 

E.g. 
https://csis.myclimateservice.eu/maintenance/resources/paths2?field_reference_type_value=All

![image](https://user-images.githubusercontent.com/2961790/61788329-2252b200-ae12-11e9-8f7f-8062051ad308.png)

versus https://csis.myclimateservice.eu/maintenance/resources/paths

![image](https://user-images.githubusercontent.com/2961790/61788401-49a97f00-ae12-11e9-9309-6f71edc2f757.png)

In my opinion, this is bad. As I stated previously, it's already bad enough to have this differentiation between "default" and "other" paths, because this is bound to make the visualization widgets design more complex but this just add more complexity.

How will the map widget know what to show? With current design, this is what it  has to do:

1) check the service tag - if it's map, then use the default path (and use the resource title as a title for the layer?)
2) check all references, add those that are of the map type to the list of the layers to show. (what to use as a layer title?)

Same for any other widget that we design. And the type one looks for is different in cases 1 and 2. 

1. If we remove the default path, No. 1 will not be necessary anymore. 
2. If we assure that the same tags are used in both cases, at least the code would search for the same tag in both places.

**Comment by p-a-s-c-a-l** [comment]
> * check the service tag - if it's map, then use the default path (and use the resource title as a title for the layer?)
> 
> * check all references, add those that are of the map type to the list of the layers to show. (**what to use as a layer title?**)

@therter 

How is this implemented now in the Map Component? Take the **first** *mapView* reference, ignore all additional references, no matter if is *mapView* or not, and use the resource title as layer title?

**Comment by therter** [comment]
> How is this implemented now in the Map Component? Take the **first** _mapView_ reference, ignore all additional references, no matter if is _mapView_ or not, and use the resource title as layer title?

At the moment, the **last** reference with the type @mapview:ogc:wms is used. All other references  are ignored and the resource title is used as layer title.

**Comment by DenoBeno** [comment]
I have added a "best practice recommendation" to only use the references and avoid using the "path" in the widgets. Once this is assured, we can quietly drop the path variable. (I would be happy to hide it immediately) 

However, the second issue remains: "service type".

In my experience, one should (almost?) ALWAYS use taxonomies for this type of controlled vocabularies, but [in the references we are using a "list"](https://csis.myclimateservice.eu/admin/structure/types/manage/dp_reference/fields/node.dp_reference.field_reference_type/storage) instead of a taxonomy.

This is ugly. 

- Taxonomy list can be edited at any time, new elements added, even the old ones removed. List options not.
- Taxonomy terms can be easily listed, in fact they are automatically available through our service interface. List options not.
- Taxonomy terms can be re-used in views, in different entity types etc. Guess what? Lists can't...
- We can also easily build lists of terms that are tagged by a taxonomy (it's built-in drupal feature, nothing to do)

**_I recommend to change this data model immediately and fix the widgets and the existing data that we have today rather than to risk having much more work with this later._**

**Comment by DenoBeno** [comment]
I'll open an extra ticket for this and close this one.

**Comment by p-a-s-c-a-l** [comment]
> Once this is assured, we can quietly drop the path variable.

No, it's there for a reason. Please read the specification.

> This is ugly.

No, at API level, taxonomies are **really** ugly. Strings are clean and simple (KISS).

We don't need taxonomies at all levels. In most cases we don't use the perceived benefits of taxonomies. (YAGNI)

> I recommend to change this data model immediately and fix the widgets

**NO**. **NOT AGAIN**. We are spending more time "fixing" our widgets than for actual developments that brings us really forward. This must stop **now**.
