### ISSUE TITLE
Data Package resources: Details only open for topmost field

### ISSUE THREAD

**Issue by Itsman-AT** [clarity-h2020/data-package#29]
When clicking the details in the DC3 Data Package (https://csis.myclimateservice.eu/node/733), only the topmost ("Urban Atlas") resource's Details field is opening. When one clicks on the Details of the lower two, only the Details of the "Urban Atlas" resource is opening and closing.

![grafik](https://user-images.githubusercontent.com/41750112/62069059-b8824000-b237-11e9-8903-e8180a9e1231.png)

**Comment by p-a-s-c-a-l** [comment]
I cannot reproduce the problem:

![details](https://user-images.githubusercontent.com/1788226/62108020-3cc0db80-b2a9-11e9-9828-1a77031d5f6d.gif)

**Comment by DenoBeno** [comment]
This seems to happen ocassionaly, I have no idea how or why. Could be a
caching issue after the update.

**Comment by Itsman-AT** [comment]
Ok, now it is also working for me. Closing the issue. Thanks for your testing.
