### ISSUE TITLE
Use the references property for all widgets

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#32]
As explained in [Why do we need the default path?](https://github.com/clarity-h2020/data-package/issues/27), In DP resources, we currently have the "default path" (==path) and the "alternative paths" (==references). 

Default path is not needed and only complicates things. Therefore, it should not be used by any of our widgets. When it becomes safe to do so, the "path" should be removed and only the "references" kept.

Note that the references can be rearranged by users - thus we can always assume that the first one is the "default path" if this is of importance.

**Comment by p-a-s-c-a-l** [comment]
> When it becomes safe to do so, the "path" should be removed and only the "references" kept.

No, that is the **main** resource location and it usually should not show up under references. You are right, references is for widgets. But the default path is still needed. See documentation in https://github.com/clarity-h2020/data-package

> Note that the references can be rearranged by users - thus we can always assume that the first one is the "default path" if this is of importance.

No, the order is not guaranteed. What you get at API level may be different from what you see in Drupal.

**Comment by DenoBeno** [comment]
The order is guaranteed. Drupal sorts the referenced fields by weight per default.

OK: the order *should* be guaranteed. This should be easy to check, unfortunately I don't know which link is used by JSON:API. If JSON:API doesn't sort the references correctly, I'll issue a bug upstreams - it should.
