### ISSUE TITLE
Data package Best practice recommendations

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#33]
Please follow this link for a list of best practice recommendations related to the data package

* [Data Package best practice recommendations](https://github.com/clarity-h2020/data-package/issues?utf8=%E2%9C%93&q=label%3A%22best+practice%22+)
* [Generic CSIS best practice recommendations](https://github.com/clarity-h2020/csis/issues?utf8=%E2%9C%93&q=label%3A%22Best+practice%22+)

Please note that the data package recommendations are often also valid for any other CSIS development and vice versa.

_Please add more "best practices" as necessary._

**Note:** an alternative way for finding the best practices is through the wiki.

**Comment by p-a-s-c-a-l** [comment]
IMHO the [WIKI](https://github.com/clarity-h2020/data-package/wiki) is a better place for this. Issues are not meant as knowledgeable but as concrete tasks.

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l  I have added a shot text and a link to the wiki. Maintaining the list through issue tickets is easier and I don't like the way how wiki works with multiple pages (or the idea of having all text in one page).

I've also noticed that it's possible to move the issues across packages, so I guess that all these recommendations will end up under CSIS in the end.
