### ISSUE TITLE
Fix the dp_reference data model

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#34]
dp_reference us the "list" instead of the taxonomy references for field_reference_type. In my experience, one should (almost?) ALWAYS use taxonomies for this type of controlled vocabularies:

- Taxonomy list can be edited at any time, new elements added, even the old ones removed. List options not.
- Taxonomy terms can be easily listed, in fact they are automatically available through our service interface. List options not.
- Taxonomy terms can be re-used in views, in different entity types etc. Guess what? Lists can't...
- We can also easily build lists of terms that are tagged by a taxonomy (it's built-in drupal feature, nothing to do)

I therefore recommend to change this data model immediately and fix the widgets and the existing data that we have today rather than to risk having much more work with this later.

On a related note, the list of possible service types is incomplete and we have to extend it . Doing this with the current data model is a very bad idea. Once we switch to taxonomies, we can even use the "select or else" widget to simplify defining of new service types if we want to. (I believe that the users who aren't administrators will not even see the "else" part...)

**Note:** dp_reference also uses free text for the field_reference_qualifier. We should re-think this one too.

**Comment by DenoBeno** [comment]
We (AIT) can fix this, but we don't want to break any currently working widgets. It would be therefore important to know who/where/how is currently using this field first.

**Comment by p-a-s-c-a-l** [comment]
> ... but we don't want to break any currently working widgets.

OK, then we agree. **No changes to the data model any more**. Don't try to make it "perfect". This is not possible.

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l : it's not the question of making it perfect. It's a question of making it usable.

We have to add service types - e.g. several for the emikat views. I don't even know how many different ones we have to add, but I presume that the widgets will have to differentiate at least between Emikat json, csv or XML views. Maybe that's enough, maybe we'll need more - difficult to say today.

**Comment by p-a-s-c-a-l** [comment]
>  I don't even know how many different ones

Me neither. And that's exactly the reason why I want to follow the [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) principle.
