### ISSUE TITLE
Fix the dp spatial extents

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#39]
While improving the resource and data package editing, I realized that the spatial extent could be useful and re-introduced it in the "simple" edit mode.

However, I had to add a geospatial data element to make it possible to visualize the bounding box easily. Result is a data model that has five fields:

- one geospatial bounding box
- four text fields with the geospatial coordinates.

This isn't a big deal because only few people will ever see the edit form of the dp_spatial_extent, but it's ugly and it would be better to fix it eventually. 

**Question:** is this data used for anything now? If not, we can just delete it immediately.

**Comment by DenoBeno** [comment]
Related question: there are some old spatial extents defined. Can these be deleted, or are they used for something? They are in the way now...

**Comment by therter** [comment]
> **Question:** is this data used for anything now?

I do not use this data in the react components, but I don't know if they are used somewhere else.

**Comment by p-a-s-c-a-l** [comment]
ATM we don't use the spatial extent of the resource, but we are planning to use it in order to set an initial bounding box when eventually showing the map component in resource / data package views. So for us it's just important to know which filed(s) will definitely stay in the data model. Anything that's not needed should be removed asap so that we don't end up in a situation where we rely on wrong and outdated parts of the data model.

**Comment by DenoBeno** [comment]
OK, fixed. I have also removed all old entries, and renamed the old fields into "remove ...". If they are found in any views, they should be deleted.

**Comment by DenoBeno** [comment]
We might still have an issue here: as I learned today, you aren't using the same projection in the project widgets as the google and co use per default. 

So now we have the BBs defined in such a way that they can be shown on a maps generated by drupal modules, whihch is useful. Unfortunately, they are in the "wrong" projection for use by the widgets you produced. 

What now?

**Comment by p-a-s-c-a-l** [comment]
BBS? widgets? modules? Sorry, I've lost track. 
Anyway, we agreed on EPSG:3035 as default CRS long time ago. Most spatial data is generated in EPSG:3035. EPSG:3035 is used internally in EMIKAT, too. I you want to change that to EPSG:4326, you have to talk to @humerh first.

Anyway, the map component doesn't care about de different geo_fields except for the geo_field in the cities taxonomy which is EPSG:3035.

**Comment by DenoBeno** [comment]
Sorry, I'll try to be clearer.

I have recently set up the "dp_spatial_extent" in such a way that users can easily add new spatial extents and that this information is immediately shown on a map using the drupal-internal mechanism.
The same is true for the coordinates used in "twins" and in the "showcases". I suppose they are all in EPSG:4326.

I only realised that this uses a different projection than the rest of the system when I saw the cities taxonomy...

I don't see any configuration option for setting the projection within drupal geospatial modules stack, so we are stuck with EPSG:4326 for now.

The problem is that dp_spatial_extent is deemed to be used by the (future) map widget when data is visualised outside study.

I suppose the "helper module" will have to take care of reprojection. :-(

**Comment by p-a-s-c-a-l** [comment]
Re-projection could be handled inside the map component, but we'll better [re-import the cities taxonomy in EPSG:4326](https://github.com/clarity-h2020/docker-drupal/issues/68#issuecomment-521111723) while the original data served by Geoserver [will remain in EPSG:4326](https://github.com/clarity-h2020/local-effects/issues/5#issuecomment-520908918).

**Comment by DenoBeno** [comment]
I had a bit more testing with the drupal now and found out that all drupal geospatial fields are hardcoded to EPSG:4326. If you try to enter the data in EPSG:3035, it will complain "out of bounds" and not let you do so.

**This kind of concludes the issue on the drupal side: we can only store the geospatial data in EPSG:4326. If we want to store the data in a different projection, this can only be done in a text or numeric field.** 

For the dp_spatial_extent, I have re-enabled the minx/miny/maxx/maxy fields again now, so that the data for our map widget can be entered if needed (if the map component handles the re-projection on its own, this can be inored & deleted). For all other instances where we use geospatial fields in drupal, there is *currently* no expectation that the csis map will present the data => this can be ignored.

Closing the issue again. 

If we really need the EPSG:3035 data in the dp_spatial_extent, this data *can* be added per hand or by some process either now or later. If not, even better.
