### ISSUE TITLE
1st Data Package: 00 Background Layers

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#4]
This set of tasks relate to making numerous **default** background / inventory layers available in the CSIS Map Component. While those layers are not directly used for impact/risk calculation with or without adaptation, internally they may serve as input for creating (local effects) hazard or exposure layers (see https://github.com/clarity-h2020/csis/issues/33 and in particular [Modelling Workflow.pptx](https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=%2FCLARITY%2FWP4+Technology+Support%2FT4.2+Catalogue+of+Elements+at+Risk+and+Adaptation+Options%2FModelling+Workflow&scrollto=model+workflow.pptx) for more details.

Interestingly, those layers are independent of a particular Data Package or Use Case. Thus they can be considered **default** layers that are available in **any** Data Package. In addition to that **tailored Data Packages** may include additional background layers, e.g. [high-resolution city models](https://www.avoindata.fi/data/en_GB/dataset/helsingin-3d-kaupunkimalli) used as input for local (hazard) models.  

Usually, there is no direct user-interaction (get feature info, modify features) with these layers. Even if some of these layers may show some kind of 'Elements at Risk', they are still **not** subject to modification by adaptation options, since they need to be 'rasterized' to qualify as actual Exposure Layers. (This special case has to be considered in the task for making available Exposure Layers). Therefore it is usually not needed to access theses Layers via WCS/WFS interface. Moreover, to speed up rendering in the Map Component (Leaflet.js) and to support webbrowser-based caching of tiles, such static layers that don't change (often) should be proxied by [GeoWebCache](https://www.geowebcache.org/) and accessed via the respective TMS/WMTS service interface.

The following tasks which will be broken down in the respective repositories (e.g. [Map Component](https://github.com/clarity-h2020/map-component/issues)) into several other issues can be identified:

- [ ] [1st Data Package: Background Layers - 1) Create Layers ](https://github.com/clarity-h2020/data-package/issues/5)
- [ ] [1st Data Package: Background Layers - 2) Create Data Resource](https://github.com/clarity-h2020/data-package/issues/7)

**Comment by RobAndGo** [comment]
@maesbri 
I'm not sure if this belongs here, but here are the data package json files for the summer days, hot days, and tropical nights hazard characterisation index on the European level. I had to include the suffix .txt in order that github allowed me to upload the file.

[data_package_heat_indices_summer_days.json.txt](https://github.com/clarity-h2020/data-package/files/3349255/data_package_heat_indices_summer_days.json.txt)
[data_package_heat_indices_hot_days.json.txt](https://github.com/clarity-h2020/data-package/files/3349256/data_package_heat_indices_hot_days.json.txt)
[data_package_heat_indices_tropical_nights.json.txt](https://github.com/clarity-h2020/data-package/files/3349257/data_package_heat_indices_tropical_nights.json.txt)


Each resource within the data package gives the:
a) model ensemble mean (odd numbered resources)
b) model standard deviation (even numbered resources)
for each of the periods:

- baseline period (1971-2000)
- rcp26 (2011-2040, 2041-2070, 2071-2100)
- rcp45 (2011-2040, 2041-2070, 2071-2100)
- rcp85 (2011-2040, 2041-2070, 2071-2100)

That is, there are a total of 20 resources within this data package.

I have uploaded the corresponding data here:
/clarityftp/europe/hazard_indices/heat/summerdays/
/clarityftp/europe/hazard_indices/heat/hotdays/
/clarityftp/europe/hazard_indices/heat/tropicalnights/

**Comment by p-a-s-c-a-l** [comment]
IMHO this fits into the [HC part](https://github.com/clarity-h2020/data-package/issues/11) of the Data Package. But ATM I not sure what we can do with this data in CSIS. 

@ghilbrae  @luis-meteogrid Can we import it into METEOGRID Geoserver to show it on the Map? Would that make sense? But ATM we have more important things to important things to do, so I would put this task on hold.

**Comment by ghilbrae** [comment]
@p-a-s-c-a-l there's no problem on our side, we can upload the new layers in no time.

**Comment by p-a-s-c-a-l** [comment]
Some background Layers are available in [HC-LE](https://github.com/clarity-h2020/data-package/issues/8). This is not optimal, but the best get can get ATM.

**Comment by p-a-s-c-a-l** [comment]
See https://github.com/clarity-h2020/csis/issues/105#issuecomment-538278802
