### ISSUE TITLE
Which EMIKAT-generated resources do we need to include in the screening Data Package(s)?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#42]
This is related to https://github.com/clarity-h2020/data-package/issues/18 and https://github.com/clarity-h2020/csis/issues/91
Also related to: https://github.com/clarity-h2020/data-package/issues/45, https://github.com/clarity-h2020/data-package/issues/46, https://github.com/clarity-h2020/data-package/issues/47, https://github.com/clarity-h2020/data-package/issues/49

**Issue at hand:** if I understand our application model correctly, _we have to list all the EMIKAT results as ressources with EMIKAT-specific variables in the URIs in the Data Packages that will be used for screening_. Otherwise CSIS will not be able to visualize them.

@p-a-s-c-a-l , @helllth : is this correct/is this the way to go or not?

One example of such a resource is the "population density within the EU-wide data package (see https://csis.myclimateservice.eu/node/682 and https://csis.myclimateservice.eu/node/754)

@humerh: Which other resources is EMIKAT producing (or will produce) that need to be listed in this ? Impact tables? Impact maps? Impact tables and maps with adaptation options applied (in development/future)? Other? What are the links that need to be added?

Alternatively, we could produce special "screening" versions of the embedded applications that know what needs to be done. This would make it easier to produce screening data packages, but we would have to invest more in javascript application developments. 

@p-a-s-c-a-l , @helllth : which way should we go in your opinion?

Any other issues that you are aware of, or ideas how to handle this?

**Comment by DenoBeno** [comment]
This is pretty much a showstopper IMO. We have to resolve this in order to produce screening results.

**Comment by p-a-s-c-a-l** [comment]
I want to keep everything as it is now! That is, no special apps for screening. Our current apps will replace EMIKAT variables like $emikat_id in resource URIs with values obtained from concrete studies.

This works and is implemented in the new map component. So **there is no need for further action here**.  

ATM deployment of the new map component is delay until https://github.com/clarity-h2020/csis-helpers-module/issues/10 is implemented.

**Comment by DenoBeno** [comment]
OK, but I presume that we still miss some resources in the data package ATM. E.g., there are no resources corresponding to EMIKAT impact calculation in the data package atm. Or are they?

**Comment by DenoBeno** [comment]
OK, I have just discussed this with Heinrich, and we have defined a second EMIKAT-generated data layer for the european data package: 

https://csis.myclimateservice.eu/node/1272

This is based on the information in the wiki: https://github.com/clarity-h2020/csis/wiki/Services-endpoints-(used-by-CSIS)

![grafik](https://user-images.githubusercontent.com/2961790/64160838-f0833100-ce3c-11e9-8a82-fecb2fcc436d.png)

etc.

As you can see, there is a whole lot of variables in this resource file. E.g.:

https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Aview.2974&bbox=4672000.0%2C1979500.0%2C4687500.0%2C1988000.0&width=768&height=421&srs=EPSG%3A3035&format=image%2Fgif&CQL_FILTER=PROJECT%3D**$emikat_variant**%20and%20PERIOD=%27**$emikat_period**%27%20AND%20RCP=%27**$emikat_rcp**%27%20AND%20FREQUENCE=%27**$emikat_frequency**%27%20AND%20SZ_ID=**$emikat_id**&styles=T_A

See the wiki page for explanation of possible values for each of the variables.

An alternative would be to produce a ressource fiel for all combinations of the parameters, but this would be completely a nightmare to maintain.

How to proceed with this?

**Comment by DenoBeno** [comment]
The third resource produced by emikat is the "Impact Calculation (Mortality) for each Scenario, Time period, typical Events and for each Adaptation Project", also described in the wiki. Will require the same variables.

**Comment by p-a-s-c-a-l** [comment]
Following steps are required to make this work:

1) Variables have to be stored in the study or gl_step entity -> somebody has to extend the data models
2) variables are made available as JavaScript variables -> somebody has to extend the csis_helpers_module (see https://github.com/clarity-h2020/csis-helpers-module/issues/10)
3) variables are supplied by the users => somebody has to implement a use interface for this (see https://github.com/clarity-h2020/docker-drupal/issues/58)
4) variables are evaluated by the map / table component to generate the parametrised EMIKAT URIs =>CIS has to extend Table and Map Components

**Comment by DenoBeno** [comment]
OK, I had some house-internal discussion on how to get this started and here is one idea for discussion:

1) Variable names should not be $name but rather ${name} (shell notation) or {{name}}/{{ name }} (twig notation, spaces are ignored) or such - something that's easier to parse. I don't really care what, but with $name it's difficult because it's not so clear where it ends. And having variables called $name and $name2 would cause havoc. (thanks Heinrich)
2) With exception of the emikat_id, other variables should not have emikat in name. So maybe we should call them  csis_something or CSIS_something. Or even drop the "csis" part.
3) Hard-coding the possible variable values in the CSIS or in javascript viewers is a particularly bad idea. E.g., maybe some resource allow {{ RCP }} as a variable, but provides the data only for "baseline" and "rcp45" scenarios.

So, I would propose to add a taxonomy of possible variable/value combinations to the system. This taxonomy would have the following fields:

- **Title:** automatically generated form field_var_name and field_var_value
- **field_var_name**: one from a list of supported variables, e.g. RCP, frequency, 
- **field_var_value**: free text
- 

Example: 

- **Title:** RCP: rcp45
- **field_var_name**: RCP 
- **field_var_value**: rcp45

If necessary, we can adopt some naming convention so that e.g. ranges of allowed of values can be indicated too. E.g. RANGE(2020;2050;10). I would rather hope that we don't need this, but it's possible to do if and when needed, so the concept sounds OK to me.

Once such taxonomy exists, we could add "Allowed variable values" field that point to this taxonomy and let the owner of the ressource indicate which variable values are valid with their ressource by linking all the relevant ones with the resource.

Thus, the EMIKAT resource listed above would have a following list included:

- period: baseline (which is?)
- period: 2011-2040 (or 20110101-20401231?)
- period: 2041-2070 
- ...
- RCP: baseline
- RCP: rcp26
- RCP: rcp45
etc.

I'm not sure what to do with "emikat_id" and the "project" variables that do not have a pre-set range of allowed values. Maybe something like this, to indicate that the allowed values will be defined in the project?

- emikat_id:$project_emikat_id
- project: BASELINE
- project: $project_variant 

**Questions:**
1. Should we follow up on this or do you have a better idea how to do it?
2. which variable naming convention to use?

**Comment by DenoBeno** [comment]
For example, we could use of twig notation {{ }}, and to name the variables in the following way:

- project specific ones with project prefix.  E.g. {{ project_emikat_id }}, {{ project_variant }}
- resource specific ones with no prefix or with csis prefix. E.g. {{ rpc }} or {{ csis_rpc }}
- capitalization: ignore capitalization or all lowercase if this isn't an option. So either we only use rpc or  we consider {{ RPC }} and {{ rpc }} to be the same.

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l : this would obviously be just a first step. Once we do have this information, the site functionality would have to be redesigned to use it as you already indicated. In the meantime:

- everything that doesn't use the variables should continue working as it does now in the meantime
- resources that do use these variables would only work in the parts of the site where a change has been implemented...

**Comment by p-a-s-c-a-l** [comment]
Let me finish the 1st map and table that work with the already available $emikat_id and then we can continue the discussion.

**Comment by p-a-s-c-a-l** [comment]
At least the following files from different repositories are affected and need to be changed, therefore I would appreciate a **final** decision on the parameter names. Any later change will become costly otherwise.
- [ ] [EMIKATHelpers.js](https://github.com/clarity-h2020/csis-helpers-js/blob/dev/src/lib/EMIKATHelpers.js)
- [ ] [csis_helpers.module](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/csis_helpers.module)
- [ ] [csis_iframe_connector.js](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/js/csis_iframe_connector.js)
- [ ] [BasicMap.js](https://github.com/clarity-h2020/map-component/blob/dev/src/components/commons/BasicMap.js).
- [ ] [drupalService.js](https://github.com/clarity-h2020/scenario-analysis/blob/dev/app/scripts/services/drupalService.js)
- [ ] [RiskAndImpactTable.js](https://github.com/clarity-h2020/table-components/blob/dev/src/components/RiskAndImpactTable.js)

To keep it simple and straightforward, i propose the following names:

```js
/**
 * The EMIKAT STUDY ID
 * 
 * @type {String}
 */
export const EMIKAT_STUDY_ID = '$emikat_id';

/**
 * PROJECT=BASELINE ... (for future selection of an alternative ADAPTATION variants)
 * 
 * @type {String}
 */
export const EMIKAT_PROJECT_VARIANT = '$emikat_variant';

/**
 * PERIOD='Baseline' ... (Alternatives are: '20110101-20401231', '20410101-20701231' and '20710101-21001231')
 * 
 * @type {String}
 */
export const EMIKAT_PERIOD = '$emikat_period';

/**
 * RCP='Baseline' ... (Alternatives are: 'rcp26', 'rcp45' and 'rcp85')
 * 
 * @type {String}
 */
export const EMIKAT_RCP = '$emikat_rcp';

/**
 * FREQUENCE='Rare' ... (Alternatives are: 'Occassional' or 'Frequent')
 * 
 * @type {String}
 */
export const EMIKAT_FREQUENCY = '$emikat_frequency';
```

**Comment by DenoBeno** [comment]
As I said before, I don't think that we should limit this only to emikat-generated resources. Even the standard resources that aren't produced on the fly would be easier to define if people could use variables and thus define just one resource instead of N.

E.g. - we have tons of heat hazard resources that have to be include in the data package and that differ just in some parameters. By using the variables, we could drastically simplify the data package.

In addition, I don't think that we should "hide" all this information in the helpers module. By using taxonomy as I proposed, we would have an easy(er) way to update the available options. And it would be easy to show the options to the users when they are adding resources, too.

so emikat_id stays, but the other ones should probably be called study_X and resource_X

So these are really EMIKAT variables that change for every study:
- emikat_id
- study_variant (or emikat_variant if you prefer)

but these are not:
- resource_period, resource_rpc, resource_frequency  

We may also need study_period, study_rpc, and study_frequency - to indicate which ones are chosen for use in the study? This is not possible to do today, though.

Finally, I would suggest to use something like twig notation for variables in URI. {{ resource_frequency }} or ${resource_frequency} is certainly easier to parse that $resource_frequency when used in an URI, no?

**Comment by humerh** [comment]
I want to add, that there are a lot of other "Ressources" of WMS Layers, which are also built up by the name componetns "period", "rcp" and "fequency", and they have nothing to do with Emikat.
So I would also propose to avoid for this variables the prefix "emikat_".
For "$emikat_id" the prefix is ok, because it references an internal EMIKAidentifier.

If we use also for this layers these variables I think we can reduce a lot of resources.

**Comment by p-a-s-c-a-l** [comment]
ATM we  should consider EMIKAT generated resources only because that's what we really need **now**. So are [those parameter names](https://github.com/clarity-h2020/data-package/issues/42#issuecomment-528824498) O.K. for now?

**Comment by humerh** [comment]
As discussed in the Telco on Mon, 16.09.2019 I would propose to change the names of filter column names and the names of variables:

Filter column names:

|  Old  |  New  |
| --- | --- |
| PROJECT | STUDY_VARIANT |
| PERIOD | TIME_PERIOD |
| RCP | EMISSIONS_SCENARIO |
| FREQUENCE | FREQUENCY |


Names of variables:

|  Old  |  New  | New_2 | Alternatives
| --- | --- | --- | --- |
| $emikat_variant | $study_variant | ${study_variant} | 'BASELINE', 'ADAPTATION' |
| $emikat_period | $time_period | ${time_period} | '20110101-20401231', '20410101-20701231', '20710101-21001231 |
| $emikat_rcp | $emissions_scenario | ${emissions_scenario} | 'rcp26', 'rcp45', 'rcp85' |
| $emikat_frequency | $frequency | ${frequency} |  'Rare', 'Occassional', 'Frequent' |

**Comment by patrickkaleta** [comment]
Thank you @humerh. I think those new variable names look good. The "Alternatives" column shows all possible values for each variable, right?

**Comment by DenoBeno** [comment]
Unless Pascal has some serious issues with this, I second the "New_2" approach.

This means that we need to support the  following variables, and that all variables will need to be written as ${variable_name} in the URIs:

Just for EMIKAT resources
- emikat_id

Mostly for EMIKAT resources, possibly other:
- study_variant
- time_period (personally I find this tautology but don't care too much. Maybe **period_covered** or simply **period** would be better) 
- emission_scenario (singular emission, not emissions. Or simply "rpc")
- frequency

For the sake of typing less, we could go for "period", "rpc" and "frequency".

**Comment by patrickkaleta** [comment]
> For the sake of typing less, we could go for "period", "rpc" and "frequency".

No, we discussed that today in our telco and decided to use "emissions_scenario" instead of "rcp" etc, because that's how we named it in the data package (and probably other places) and we want to use consistent names for describing the same things to minimize confusion.

**Comment by p-a-s-c-a-l** [comment]
Thanks @humerh , I would rename frequency to `event_ frequency`. So the final set of variables would look like:

|  Filter | Variable | Alternatives
| --- | --- | --- |
| EMIKAT_ID | ${emikat_id} | *n/a* |
| STUDY_VARIANT | ${study_variant} | 'BASELINE', 'ADAPTATION' |
| TIME_PERIOD | ${time_period} | '20110101-20401231', '20410101-20701231', '20710101-21001231 |
| EMISSIONS_SCENARIO | ${emissions_scenario} | 'Baseline', 'rcp26', 'rcp45', 'rcp85' |
| EVENT FREQUENCY | ${event_frequency} |  'Rare', 'Occassional', 'Frequent' |

**Comment by DenoBeno** [comment]
OK, passt

**Comment by DenoBeno** [comment]
I am starting the work on the following, should be finished later today:

1) taxonomy of allowed variable values. This will connect emission_scenario with three possible values rpc26/45/85 and so on
2) possibility to state which of these values are applicable for a resource. This is "yet another tagging", I can just extend the existing tagging mechanism by adding a possibility to tag by yet another taxonomy. WDYT?

**Comment by p-a-s-c-a-l** [comment]
>     2. adding a possibility to tag by yet another taxonomy

yes, that's o.k.

**Comment by DenoBeno** [comment]
Question: what to do with free numbers?
1. For EMIKAT, I have indicated "[0-9]+" as allowed value
2. for the study variant, I could define ADAPTATION-01, and later ADAPTATION-02, 03 etc - as we need it. I suppose we will never have more than a handful of variants in a study. Alternatively, I could define a generic 'ADAPTATION-[0-9][0-9]'. WDYT?

**Comment by DenoBeno** [comment]
What does 'Rare', 'Occassional', 'Frequent' mean?

**Comment by DenoBeno** [comment]
Taxonomy defined. Just missing the description for the three event frequency items

![image](https://user-images.githubusercontent.com/2961790/64957734-d6f6d600-d88d-11e9-8000-0bd222ec80b0.png)

**Comment by DenoBeno** [comment]
Done. Tested for a simple case of https://csis.myclimateservice.eu/node/754

![image](https://user-images.githubusercontent.com/2961790/64960486-a5810900-d893-11e9-9917-4631324ac03f.png)

**Comment by DenoBeno** [comment]
According to https://github.com/clarity-h2020/csis/wiki/Services-endpoints-(used-by-CSIS), EMIKAT also differenciates between  styles=T_A for Apparent temperature, styles=T_TMRT for Mean Radiant Temperature and styles=T_UTCI for UTCI Temperature

Do we need this as a variable too?

**Comment by humerh** [comment]
No, I think not, as these are different Parameters with different Semantics. How do you handle this with other data Source, where the data source contains more than one Parameter? We can implement also 3 ressources.

**Comment by DenoBeno** [comment]
@humerh : this is the first time that we have introduced the variables. Please see https://github.com/clarity-h2020/data-package/issues/45 and https://github.com/clarity-h2020/data-package/issues/46 for the first trials that I have implemented now.

**Comment by DenoBeno** [comment]
Related to https://github.com/clarity-h2020/data-package/issues/42, https://github.com/clarity-h2020/data-package/issues/45, https://github.com/clarity-h2020/data-package/issues/46, https://github.com/clarity-h2020/data-package/issues/47, https://github.com/clarity-h2020/data-package/issues/49

We have defined three resources that are generated by EMIKAT and that use variables now. I am aware that we still need to add two more "local heat" resources because styles can have three values (T_A|T_TMRT|T_UTCI). That would be five "EMIKAT" resources.

**@humerh: is this all (as long as we don't have flooding hazard/vulnerability/impact), or are we still missing something?**

**Comment by DenoBeno** [comment]
From today's telco I understood that we are missing some resources that are generated by EMIKAT. Which ones?

**Comment by DenoBeno** [comment]
I can see that EMIKAT is building views with IDs 2955, 2974, 2975, 2994 and 2995 now. 

@humerh : Last two are not documented on the wiki, what do they do?

**Comment by p-a-s-c-a-l** [comment]
> From today's telco I understood that we are missing some resources that are generated by EMIKAT. Which ones?

The answer should be somewhere [in here](https://github.com/clarity-h2020/emikat/issues/25). [here](https://github.com/clarity-h2020/local-effects/issues/5) or [here](https://github.com/clarity-h2020/emikat/issues/26). IMHO mortality rates and azimuth are either missing or already part of another resource.

**Comment by DenoBeno** [comment]
> > From today's telco I understood that we are missing some resources that are generated by EMIKAT. Which ones?
> 
> The answer should be somewhere [in here](https://github.com/clarity-h2020/emikat/issues/25). [here](https://github.com/clarity-h2020/local-effects/issues/5) or [here](https://github.com/clarity-h2020/emikat/issues/26). IMHO mortality rates and azimuth are either missing or already part of another resource.

 2955, 2974, 2975, 2994 and 2995 do not appear on the linked pages.

**Comment by p-a-s-c-a-l** [comment]
IMHO this can be closed.
