### ISSUE TITLE
Should EMIKAT read the input data from the data package?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#43]
Related to: 
- https://github.com/clarity-h2020/data-package/issues/42
- https://github.com/clarity-h2020/data-package/issues/18 and 
- https://github.com/clarity-h2020/csis/issues/91

Currently, EMIKAT "knows" which data to source for its calculation and whatever we include in the Data Package is just optional/for information. 

**Advantage:** easier to do from EMIKAT side, robust as calculation will always work.
**Disadvantage:** not flexible, can lead to mismatch, if EMIKAT uses one input data and a different input data is shown in the DP.

**For discussion:** what should we do about this, if anything?

As I see it, our options are "leave as is" or "do it properly". ATM, I'm inclined to say "just leave it as it is for now", but we must be aware what this means:
- EMIKAT always uses the same data for calculations (no flexibility)
- Whatever input data is in the DP will be ignored by EMIKAT (DP and EMIKAT will eventually go out of sync, maybe they already are)

**Comment by p-a-s-c-a-l** [comment]
I strongly support "leave as is" as I don't expect that you'll ever need that flexibility (YAGNI) since I'm pretty sure that we  won't produce additional screening data  packages.

**Comment by DenoBeno** [comment]
OK, I second this. 
If we ever come to the point where this may be useful AND we have enough time, then we'll think of doing it.
