### ISSUE TITLE
We need more and better showcases and adaptation options

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#44]
I have almost finished the development of two "Adaptation options identification" views that allow the following:

1. AO table: find out which adaptation options are included in teh data package and choose some for inclusion in the report. (should work tomorrow)
2) AO twin: Search through Twins and Showcases using these adaptation options and choose some for inclusion in the report.

This gives some life to the "adaptation options identification" step and also allows us to start experimenting with screening impact calculations.

Unfortunately, we have very few sensible adaptation options to include in the data packages and even fewer showcases using these adaptation options. We need more/better ASAP.

**Comment by DenoBeno** [comment]
@RobAndGo : can you please assign some people to this?

**Comment by DenoBeno** [comment]
@RobAndGo , all: how is this progressing?

**Comment by claudiahahn** [comment]
I just noticed that: 
https://csis.myclimateservice.eu/adaptation-options-overview
Showcase “park cooling during heat wave”: wrongly connected to following adaptation options: 
-	Thermal insulation
-	Narrow streets
-	Optimize orientation to wind and sun
-	High-rise buildings (shade)

I hope to enter some showcases soon

**Comment by claudiahahn** [comment]
regarding solution-offers: 
https://csis.myclimateservice.eu/solution-offers?field_off_target_id=All&field_sector_target_id=All&field_country_target_id=7
Selection option does not work (if a country is selected – nothing will be displayed)

**Comment by DenoBeno** [comment]
> I just noticed that:
> https://csis.myclimateservice.eu/adaptation-options-overview
> Showcase “park cooling during heat wave”: wrongly connected to following adaptation options:
> 
> * Thermal insulation
> * Narrow streets
> * Optimize orientation to wind and sun
> * High-rise buildings (shade)
> 
> I hope to enter some showcases soon

Did you fix it? I have no idea what is correct/incorrect here.

**Comment by claudiahahn** [comment]
was that entered by Hand? I thought you have set up an automated way to select showcases?

**Comment by DenoBeno** [comment]
How should the CSIS know what is written in a showcase? We don't have any
AI components in this project.

**Comment by DenoBeno** [comment]
> regarding solution-offers:
> https://csis.myclimateservice.eu/solution-offers?field_off_target_id=All&field_sector_target_id=All&field_country_target_id=7
> Selection option does not work (if a country is selected – nothing will be displayed)

Fixed.

However, the *good* solution would be to use the search API. As long as we don't, even the items that have no entries will show in the pulldowns. That can be frustrating for the users.

**Comment by DenoBeno** [comment]
This should be "in progress". What is the status, btw?

**Comment by claudiahahn** [comment]
I added a solution offer from ZAMG - urban modelling group
hope to add a few showcases next week or so,

**Comment by DenoBeno** [comment]
Good! :-)

**Comment by p-a-s-c-a-l** [comment]
Any further progress to report here? :-)

**Comment by p-a-s-c-a-l** [comment]
> Any further progress to report here? :-)

Doesn't seem so. Closing.
