### ISSUE TITLE
CSIS URI variables in praxis 4 [RA/IA]: Heat mortality risk/impact

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#46]
Related to https://github.com/clarity-h2020/data-package/issues/42, https://github.com/clarity-h2020/data-package/issues/45, https://github.com/clarity-h2020/data-package/issues/46, https://github.com/clarity-h2020/data-package/issues/47, https://github.com/clarity-h2020/data-package/issues/49

I have implemented "Heat mortality risk/impact screening", please take a look
https://csis.myclimateservice.eu/node/1356/edit 

@humerh: Are the uris correct? 
@p-a-s-c-a-l: Is this how we want the variables used?
@therter: I hope that you can support this in the map soon...

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l , @therter : please note that updating of the existing heat hazard resources with resources that use variables is more important than you think. Right now, we have over 100 resources linked to "European Wide Data Package" https://csis.myclimateservice.eu/node/682. That is completely unmaintainable:

that is: it's nearly impossible to double-check if any of the resources is missing and if all of them are correctly defined. Not to mention updating anything.

**Comment by p-a-s-c-a-l** [comment]
@humerh: I replaced the template URLs listed under [Impact Calculation Service (Mortality)](https://github.com/clarity-h2020/csis/wiki/Services-endpoints-(used-by-CSIS)#impact-calculation-service-mortality-for-each-scenario-time-period-typical-events-and-for-each-adaptation-project) with some variables and got the following errors:

- [ ] https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/data?rownum=1000&filter=STUDY_VARIANT%3D’BASELINE’&filter=TIME_PERIOD%3D’Baseline’&filter=EMISSIONS_SCENARIO%3D’Baseline’&filter=EVENT_FREQUENCY%3D’rare’&filter=SZ_ID%3D2846 - **not working:** "Error during data retrieval - EMIKAT-Server.DB.ConnectionProblem: Can't access db: java.sql.SQLSyntaxErrorException: ORA-01756: Anführungsstrich fehlt bei Zeichenfolge\n - "

- [x] EMIKAT GeoJSON: https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/geojson?rownum=1000&filter=STUDY_VARIANT%3D’BASELINE’&filter=TIME_PERIOD%3D’Baseline’&filter=EMISSIONS_SCENARIO%3D’Baseline’&filter=EVENT_FREQUENCY%3D’rare’&filter=SZ_ID%3D2846 - **OK**

- [x] or CSV: https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/csv?rownum=1000&filter=STUDY_VARIANT%3D’BASELINE’&filter=TIME_PERIOD%3D’Baseline’&filter=EMISSIONS_SCENARIO%3D’Baseline’&filter=EVENT_FREQUENCY%3D’rare’&filter=SZ_ID%3D2846 - **ok**

- [ ] WMS: https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Aview.2975&bbox=4672000.0%2C1979500.0%2C4687500.0%2C1988000.0&width=768&height=421&srs=EPSG%3A3035&format=image%2Fgif&CQL_FILTER=STUDY_VARIANT%3D%27BASELINE%27%20and%20TIME_PERIOD=%27Baseline%27%20AND%20EMISSIONS_SCENARIO=%27Baseline%27%20AND%20EVENT_FREQUENCY=%27rare%27%20AND%20SZ_ID=2846 - **not working:** <ServiceException code="internalError">      Rendering process failed 10</ServiceException>

**Comment by DenoBeno** [comment]
There is a mix of various capitalizations for the variable values in the links. Not sure if that's the reason for the error, but it doesn't look correct to me:

filter=STUDY_VARIANT%3D’**BASELINE**’&filter=TIME_PERIOD%3D’**Baseline**’&filter=EMISSIONS_SCENARIO%3D’**Baseline**’&filter=EVENT_FREQUENCY%3D’**rare**’&filter=SZ_ID%3D2846 - ok

I also wonder if the single quotes can be written as ' or must be written as %27?

**Comment by DenoBeno** [comment]
I looked into https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/geojson?rownum=1000&filter=STUDY_VARIANT%3D’BASELINE’&filter=TIME_PERIOD%3D’Baseline’&filter=EMISSIONS_SCENARIO%3D’Baseline’&filter=EVENT_FREQUENCY%3D’Rare’&filter=SZ_ID%3D2846 and the output seems to be wrong to me. I also tried with 'rare', the result is the same - this filter seems to be ignored.
![image](https://user-images.githubusercontent.com/2961790/65041534-497fb880-d957-11e9-8e4b-66f0b0626efe.png)

using %27 instead of ' doesn't seem to have any effect. 

In fact, it would seem that other filters are ignored too. E.g., I'm also getting this out of it:

![image](https://user-images.githubusercontent.com/2961790/65041947-20135c80-d958-11e9-8cac-c8d800975af5.png)

**Comment by DenoBeno** [comment]
https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/data?rownum=1000&filter=STUDY_VARIANT%3D%E2%80%99BASELINE%E2%80%99&filter=TIME_PERIOD%3D%E2%80%99Baseline%E2%80%99&filter=EMISSIONS_SCENARIO%3D%E2%80%99Baseline%27&filter=EVENT_FREQUENCY%3D%27rare%27&filter=SZ_ID%3D%272846%27

does seem to work a bit better, so at least here it could be the quotes. (I replaced ' by %27). But the result is empty:

![image](https://user-images.githubusercontent.com/2961790/65042232-b8114600-d958-11e9-86fb-275b6684e5b7.png)

**Comment by DenoBeno** [comment]
@humerh and I have tested this now - the filters seem to be completely broken at the moment. Possibly due to renaming of the parameters earlier today?

@humerh will fix this ASAP.

**Comment by p-a-s-c-a-l** [comment]
@humerh any news on that? Could you please post a REST API URL that actually works so that i can test my implementation in https://github.com/clarity-h2020/simple-table-component/issues/5 ?

**Comment by humerh** [comment]
This should be solved now. Sorry.

**Comment by DenoBeno** [comment]
This works now:

https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/data?rownum=1000&filter=STUDY_VARIANT='BASELINE'&filter=TIME_PERIOD='Baseline'&filter=EMISSIONS_SCENARIO='Baseline'&filter=EVENT_FREQUENCY='Rare'&filter=SZ_ID=2846

Thus, this must work too:

https://service.emikat.at/EmiKatTst/api/scenarios/${emikat_id}/feature/view.2975/table/data?rownum=1000&filter=STUDY_VARIANT='${study_variant}'&filter=TIME_PERIOD='${time_period}'&filter=EMISSIONS_SCENARIO='${emissions_scenario}'&filter=EVENT_FREQUENCY='${event_frequency}'&filter=SZ_ID=${emikat_id}

**Comment by DenoBeno** [comment]
I have a problem with map. Looking at the https://github.com/clarity-h2020/data-package/issues/46, I would expect that the same link as there must work here, just "clarity:view.2974" replaced by "clarity:view.2975"

however, `https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2975&bbox=4672000.0,1979500.0,4687500.0,1988000.0&width=768&height=421&srs=EPSG:3035&format=image/gif&CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%27Baseline%27%20AND%20EMISSIONS_SCENARIO=%27Baseline%27%20AND%20EVENT_FREQUENCY=%27Rare%27%20AND%20SZ_ID=2846&styles=T_A` fails.

ah, OK - last parameter is too much. So this works:

`https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2975&bbox=4672000.0,1979500.0,4687500.0,1988000.0&width=768&height=421&srs=EPSG:3035&format=image/gif&CQL_FILTER=STUDY_VARIANT='BASELINE' and TIME_PERIOD='Baseline' AND EMISSIONS_SCENARIO='Baseline' AND EVENT_FREQUENCY='Rare' AND SZ_ID=2846`

And thus, this must be OK too: 

`https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2975&bbox=4672000.0,1979500.0,4687500.0,1988000.0&width=768&height=421&srs=EPSG:3035&format=image/gif&CQL_FILTER=STUDY_VARIANT='${study_variant}' and TIME_PERIOD='${time_period}' AND EMISSIONS_SCENARIO='${emissions_scenario}' AND EVENT_FREQUENCY='${event_frequency}' AND SZ_ID=${emikat_id}`

**Comment by DenoBeno** [comment]
Status: https://csis.myclimateservice.eu/node/1356 has been updated, for potential issues see https://github.com/clarity-h2020/data-package/issues/45#issuecomment-533176110

**Comment by p-a-s-c-a-l** [comment]
You can test the JSON API response with the new simple table component [here](https://csis.myclimateservice.eu/apps/simple-table-component/build/?emikat_id=2846&time_period=20110101-20401231&emissions_scenario=rcp26&event_frequency=Frequent) (need to be logged-in in CSIS in the same browser!). 

![grafik](https://user-images.githubusercontent.com/1788226/65337852-44c23b00-dbc9-11e9-84e2-603ca78c51ad.png)


You can even change the URL Template to test the other APIs like [Population Exposure](https://github.com/clarity-h2020/data-package/issues/49), but beware of the [${} pitfall]( https://github.com/clarity-h2020/data-package/issues/45#issuecomment-533590530).

**Comment by p-a-s-c-a-l** [comment]
Basic **EMIKAT parameters** are now supported in the MapComponent, which means the WMS template URL is now parametrised. No new "virtual" layers are added for all / several parameter combinations, therefore we have to work now on a parameter selection user interface (see https://github.com/clarity-h2020/csis/issues/101)

Here are two example Links to parametrised RA/IA Maps. Difference is that one Map shows Rare events while the other shows frequent Events.:

- https://csis.myclimateservice.eu/apps/map-component/build/?url=https://csis.myclimateservice.eu/&resource_uuid=346eeadd-3751-4430-8810-a0d72e587ee7&study_area=POLYGON((14.142151%2040.78717,14.142151%2040.901447,14.356384%2040.901447,14.356384%2040.78717,14.142151%2040.78717))&emikat_id=2846&study_variant=BASELINE&time_period=20110101-20401231&emissions_scenario=rcp45&event_frequency=Rare
- https://csis.myclimateservice.eu/apps/map-component/build/?url=https://csis.myclimateservice.eu/&resource_uuid=346eeadd-3751-4430-8810-a0d72e587ee7&study_area=POLYGON((14.142151%2040.78717,14.142151%2040.901447,14.356384%2040.901447,14.356384%2040.78717,14.142151%2040.78717))&emikat_id=2846&study_variant=BASELINE&time_period=20110101-20401231&emissions_scenario=rcp45&event_frequency=Frequent

However, the layers are not loaded, it seems that the server is extremely slow (see also https://github.com/clarity-h2020/emikat/issues/9#issuecomment-533990971)

**Comment by DenoBeno** [comment]
This should be OK now no?

**Comment by p-a-s-c-a-l** [comment]
OK

**Comment by p-a-s-c-a-l** [comment]
Update EMIKAT JSON API URIs has described [here](https://github.com/clarity-h2020/emikat/issues/33#issuecomment-593336482)

**Comment by p-a-s-c-a-l** [comment]
done
