### ISSUE TITLE
CSIS URI variables in praxis 1 [HC]: heat hazard indices

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#47]
Related to https://github.com/clarity-h2020/data-package/issues/42, https://github.com/clarity-h2020/data-package/issues/45, https://github.com/clarity-h2020/data-package/issues/46, https://github.com/clarity-h2020/data-package/issues/47, https://github.com/clarity-h2020/data-package/issues/49

@RobAndGo: we are starting to experiment with resources that have variables in the URIs, For a start, we need this for EMIKAT but we shall also need it to cut down the number of hazard indices to a more manageable level. 

Could you try to define *one* such resource for the testing purpose?

1. For you to see if/how the variables that we have defined map to the  resource URIs
2. For @therter (later) to see how this can be visualised.

**Comment by RobAndGo** [comment]
I have created a resource via duplication of an existing resource for this purpose, but when I try to save the data package, I get the following error:

![2019-09-17_094316](https://user-images.githubusercontent.com/45385637/65021582-b1220d80-d92f-11e9-9684-bd94edb1597f.png)

I have created a new issue on this topic [here](https://github.com/clarity-h2020/data-package/issues/48#issue-494459738)

**Comment by p-a-s-c-a-l** [comment]
Please don't "pollute" the European Data Package with such test resources. Putting the issue on hold as there is  atm more important work to do.

**Comment by RobAndGo** [comment]
Actually it was a real resource that I defined. The aspect with using the variables as names was going to come later.

**Comment by DenoBeno** [comment]
Hm. 
The european data package already has *too many* resources, I wonder if this could be causing it. There is a data package the patrick uses for testing, this one: https://csis.myclimateservice.eu/node/50

So, let me try... 

1. https://csis.myclimateservice.eu/node/50/edit spawns the JSON:API error that I keep seeing lately. It seems harmlos, but let me just mention it here: 

![image](https://user-images.githubusercontent.com/2961790/65039791-57333f00-d953-11e9-8273-44d3af8026d5.png)

2. I already have this resource linked in the data package:
![image](https://user-images.githubusercontent.com/2961790/65039837-703bf000-d953-11e9-8b11-02812283caac.png)

3. Trying to duplicate it....

![image](https://user-images.githubusercontent.com/2961790/65039956-a7120600-d953-11e9-85a9-ccc24191e0fb.png)
...
![image](https://user-images.githubusercontent.com/2961790/65039992-b729e580-d953-11e9-8267-80858cadfde7.png)

That worked without error

4. Trying to save the data package...

![image](https://user-images.githubusercontent.com/2961790/65040079-e50f2a00-d953-11e9-8aa3-b4f0fe0499e3.png)

No error..

![image](https://user-images.githubusercontent.com/2961790/65040112-f2c4af80-d953-11e9-9e95-0b93214c4d5a.png)

5. back to edit mode, the resource is in the DP:

![image](https://user-images.githubusercontent.com/2961790/65040165-0bcd6080-d954-11e9-9518-d6f14af6651f.png)

Looks OK to me. I don't know if I'm just overly paranoid, but we have over 100 resources in european DP. I am afraid that we may be hitting some limit here.

**Comment by DenoBeno** [comment]
FYI, I have finished describing the first three EMIKAT resources : https://github.com/clarity-h2020/data-package/issues/45, https://github.com/clarity-h2020/data-package/issues/46 and also https://github.com/clarity-h2020/data-package/issues/49

We did some tests, so this *should* be OK now. Once @p-a-s-c-a-l  and @therter and @patrickkaleta have managed to present these resources in CSIS, it will be time to come back to this discussion and try out describing non-EMIKAT resource in the same way. In the meantime this is on hold.

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l : it would be nice to have something similar to https://csis.myclimateservice.eu/apps/simple-table-component/build/?emikat_id=2846 that would work with heat hazard indices. This would allow us to construct and test the URIs before putting them in CSIS.

**Comment by DenoBeno** [comment]
I took a look at "HI_summer-days". There is a total of 20 such resources in CSIS today, with following variants:

- `HI_summer-days_${emission_scenario}_${time_period}_(ensstd|ensmean)`

I am not sure what are the ensstd/ensmean, but by using the emission_scenario and time_period variables we can cut this down from 20 to just 2. 

The same is true for 

- `HI_tropical-nights_${emission_scenario}_${time_period}_(ensstd|ensmean)`

Except that there are 21 of these (why?)

So, we could cut this down from 41 to 4 or even to 2 if we have additional variable for ensstd|ensmean.

same for:
- `HI_summer_days` 
- `PI_consecutive-wet-days`
- `PI_wet-days`
- `Maximum consecutive days (summer) 75th percentile, emissions scenario (${emission_scenario), period (${time_period}), (ensemble standard deviation|ensemble mean)`

If each of these also comes 10*, then by just using the two variables we could eliminate well over 100 resources.

One unpleasant news: what is called "Baseline" scenario in EMIKAT is called "historical" scenario in hazard resources. It would be good if we could fix this and adopt a single naming convention...

**Comment by DenoBeno** [comment]
I thought about the "baseline" vs. "historical" issue. There are several ways to handle this, including:

1. Demand that everyone uses the same naming conventions
2. Let the end-users realise that "baseline" and "historical" are the same
3. Build a translation mechanism into drupal.

Number 1 may be possible within the project, but we already drifted out and it's 100% sure that outsiders will not follow our naming conventions.
Number 2 is the easiest but it's plain ugly.
Number 3 sounds complicated, but it's actually easy to implement. It boils down to adding a new parameter to dp_variables taxonomy. This is what we have today:

![image](https://user-images.githubusercontent.com/2961790/65409493-25552900-dde8-11e9-83d0-f029daa4390c.png)

What we would need is a doubling of the "variable value" - once the "value for us" and another time for "value as it is in external system". 

Let's say, we include "Variable meaning" with machine name "field_var_meaning". Then we could have variable value "baseline" and  variable value "historical" both mapping to the same "variable meaning". Then the CSIS knows that this are just two ways how external systems call the same variable. 

I suspect that we'll need the same for time periods - some people will write 2011-2040, other will write 20110101-20403112 and it's the same period.

**Comment by RobAndGo** [comment]
@DenoBeno The idea behind "ensmean" and "ensstd" is that the "ensmean" represent the mean calculated from the ensemble of climate models (4 at this stage) and "ensstd" is the standard deviation calculated from the ensemble of climate models.

I thought about joining both of these (ensmean, ensstd) into one resource by supplying two links for the "Download path" and "Service path", which I have done for the resource **PI_consecutive-wet-days_rcp26_20110101-20401231**. However, in the map preview, only the first link can be displayed, so I'm not sure how useful this would be.

**Comment by p-a-s-c-a-l** [comment]
> However, in the map preview, only the first link can be displayed, so I'm not sure how useful this would be.

Yes, the Map supports only one WMS link per resource.

**Comment by DenoBeno** [comment]
I see. These two resources indeed logically belong together. walue+how good
the value is.

Unfortunately I have no magic idea how to handle this atm. Hard-coding this
semantics in the programs showing the data would definitely not be a good
way IMO.

**Comment by DenoBeno** [comment]
Reminder: resolving https://github.com/clarity-h2020/csis-helpers-module/issues/14#issuecomment-535830997 is a pre-requisite for resolving this issue.

**Comment by p-a-s-c-a-l** [comment]
I've started implementing support for such template resource (= resources with variables) in https://github.com/clarity-h2020/csis-helpers-js/issues/8. The basic idea, as I understood, is to create for each template resource "virtual" map layers for all possible variable combinations (= template resource expansion), eliminating the need to create e.g. resources for each time_period and rcp combination.

However, the question is still how this should be used and whether it can be used at all. The expected behaviour is not clear, especially in combination with "[Study Presets](https://github.com/clarity-h2020/csis/issues/108)" (= scenarios):

The Study Preset defines the variables combinations that are applied to the Resource URI Template, e.g. replacing `${emission_scenario}`, `${time_period}` etc. by the *values* defined in the Study Preset *that is chosen by the user*. This is already implemented and applied to EMIKAT Resources, e.g. [here](https://github.com/clarity-h2020/data-package/issues/45).

It could be applied to any other type of resource if we just include the respective ${variables} in the URI (references of type mapview:ogc:wms). This will workout of the box now. Of course, it will only work inside a study **if a Study Preset (scenario) is available**. 

So, what else do we need that goes beyond this functionality? Template resource expansion *without* Study Preset? Would that make sense? Is there a use case for that?

**Comment by p-a-s-c-a-l** [comment]
ATM the feature of automatic Template Resource Expansion is enabled for Template Resources of type *background-layer*  and the variable *layer* as explained [here](https://github.com/clarity-h2020/map-component/issues/69#issuecomment-558206120). 

Other Resources are **not automatically** expanded for the reasons mentioned [above](https://github.com/clarity-h2020/data-package/issues/47#issuecomment-557562073) and in [this comment from November 2018](https://github.com/clarity-h2020/data-package/issues/2#issuecomment-441222978). 

Thus, [the initial problem](https://github.com/clarity-h2020/ckan/issues/9) of too many hazard resources **both** in the Data Package and in the Map Component (hundreds of layers) will be solved by a combination of variables in resource URIs and presets/scenarios selection, but not by *automatic* resource expansion as currently enabled for *background-layer*s.
