### ISSUE TITLE
EMIKAT,  scales for the heat indices need to be optimized

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#56]
Related to https://github.com/clarity-h2020/map-component/issues/64 and https://github.com/clarity-h2020/data-package/issues/53

For EMIKAT, I have noticed that scales for the heat indices are not good. E.g. the Ageos dimitrios study:

historic data, yearly events
- T_MRT = 74 to 103 °C
- T_UTCI = 51 to 58 °C
- T_amb = 35 to 41 °C
Worst case, 20 years events
- T_MRT = 86 to 114 °C
- T_UTCI = 63 to 70 °C
- T_amb = 43 to 49 °C

Forr all three indices, the scale is the same, 20-100°C, although T_MRT never goes below 74°C and T_ambient never above 50°C. Consequently, almost nothing is seen on a map.

E.g. T_UTCI:
![grafik](https://user-images.githubusercontent.com/2961790/67203227-e2986800-f40a-11e9-8164-c529f35afb68.png)

The green-yellow-red scala used here is not bad by the way. We could use this and add lila & blue below green and brown above red for even more contrast.

_Originally posted by @DenoBeno in https://github.com/clarity-h2020/data-package/issues/53#issuecomment-544481564_

**Comment by DenoBeno** [comment]
In the meantime, we have confirmed that EMIKAT does produce three scales for these three indices. 

`https://service.emikat.at/geoserver/clarity/wms?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=clarity:view.2974&style=clarity:T_A`

`https://service.emikat.at/geoserver/clarity/wms?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=clarity:view.2974&style=clarity:T_UTCI`

`https://service.emikat.at/geoserver/clarity/wms?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=clarity:view.2974&style=clarity:T_MRT`

At the moment only the T_A is different, but all three need to be rescaled. The question is: what should be the scales?

T_A is always the lowest, I doubt that it will ever go over 50°C. T_MRT is the highest. But what are the values one should be able to discern? The lower the difference between minimum and maximum, the better will the resolution be, but this must work in Athens as well as in Trondheim...

@mattia-leone , any suggestions?

**Comment by p-a-s-c-a-l** [comment]
Any progress here? Is this still important / relevant?
AFAIK supporting better (dynamic) scales would require to implement a SLD  in EMIKAT Geoserver. Do we have time and resources to do that?

**Comment by humerh** [comment]
Denis and I adapted the SLD definition 2 weeks ago.
The Temperature range is now in range of the new results  30 - 65 degrees.
