### ISSUE TITLE
Improve readability of the Specification

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#6]
The [Tables](https://github.com/clarity-h2020/data-package/wiki/Specification:-CLARITY-Data-Package-(General)) of the CLARITY-Data-Package Specification are not very readable. Since this is a [general problem](https://github.com/isaacs/github/issues/346) of GitHub wiki pages, we should seek for an alternative. GitHub Markdown supports HTML Tables, too.

We could put a couple of Markdown files in the /docs folder of this repository and publish it as [GitHub Page](https://blog.github.com/2016-12-09-publishing-with-github-pages-now-as-easy-as-1-2-3/) ([clarity-h2020.github.io/data-package](https://clarity-h2020.github.io/data-package)). E.g. the content of [wiki/Home](https://github.com/clarity-h2020/data-package/wiki/Home) would then be put into [docs/readme.md](https://help.github.com/articles/about-readmes/), [wiki/Specification:-CLARITY-Data-Package-(General)](https://github.com/clarity-h2020/data-package/wiki/Specification:-CLARITY-Data-Package-(General)) into e.g. docs/data-package.md, etc.

**Comment by maesbri** [comment]
Yes ... I am aware of the issue but couldn't improve it that much in the wiki page.

I'll check your suggestion.

**Comment by maesbri** [comment]
I have moved the detailed specification to the 'docs' folder.

Overall readability has improved, howver the first table (both in the general and resource documents) still shows the horizontal scrollbar, whereas the other tables fit perfectly to the area available.

I think it must be some problem to the word wrapping of the sentences  but I couldn't figure out how to fix it for those tables (they look similar to the other ones).

**Comment by p-a-s-c-a-l** [comment]
If the .md files are rendered as GitHub pages from the /docs folder, the tables look fine. 

- https://clarity-h2020.github.io/data-package/data-package-general
- https://clarity-h2020.github.io/data-package/data-package-resource

Now you just have to put the readme.md into the /docs folder and add links links the above URls.

**Comment by p-a-s-c-a-l** [comment]
[data-package-resource](https://github.com/clarity-h2020/data-package/blob/master/docs/data-package-resource.md) is missing spatial_context object, temporal_context object and analysis_context object.

**Comment by maesbri** [comment]
Yes, I am aware of that. The data package specification in github is a bit outdated.
I have been working in the update of the specification in an Enterprise Architect project the last week (before I left for holidays) but it is not finished yet. 

I am following now this approach given the complexity involved in pieces of information needed in each of the workflow steps (I am trying to model also the information in each step, even if it is not directly involved in the data package itself) just to have a better understanding of what it is needed.

In any case, I think it is a good exercise, having in a single document all CLARITY models described. The outcome of this can be later be used as input for our deliverables.

PS: Find here attached the current version. Still a lot of work pending and some things that may change in the Data Package specification, but just for you to have a peek of the current work. I plan to upload it to github when I have more stable specification.

[clarity-data-models-v0.5.eap.zip](https://github.com/clarity-h2020/data-package/files/2662793/clarity-data-models-v0.5.eap.zip)

**Comment by p-a-s-c-a-l** [comment]
Ok, thanks! Then I propose to implement the improvements we collect in [this issue](https://github.com/clarity-h2020/data-package/issues/9) first and update the specification later.
