### ISSUE TITLE
Riga should be included in the european data package

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#62]
We need Riga for the climatefestival (Final event of CLARITY). As far as I can see, the input data is available, but the Riga region is not included in the list of the available cities/regions for the screening.

Please check why and add Riga to the list of available cities/regions if possible. 

Here are some other major cities in the region that would be nice to have:
- [ ] **Riga - stree tree layer not available atm.** _City code LV001C1_
- [x] Tallin (https://csis.myclimateservice.eu/taxonomy/term/5287)
- [ ] Vilnius - stree tree layer not available atm. 
- [x] Kaunas (https://csis.myclimateservice.eu/taxonomy/term/5437)
- [x] Gdansk/Poland (https://csis.myclimateservice.eu/taxonomy/term/5603)
- [x] Helsinki/Fi (https://csis.myclimateservice.eu/taxonomy/term/5531)
- [ ] Turku/Fi - stree tree layer not available atm. 
- [ ] St. Petersburg/Ru - data for Russia not available
- [ ] Kaliningrad/Ru. - data for Russia not available

Unfortunately, the data for Russia is not available at all and **for Riga/Villnius and Turku, at least the Stree Tree Layer is not available => these cities can't be supported at the moment.**

**Comment by patrickkaleta** [comment]
> Please check why and add Riga to the list of available cities/regions if possible.

@therter's import script would've have included Riga in our [Cities/Region](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/cities_regions/overview) taxonomy if it had all required input data/layers available. But I'm guessing for Riga this just wasn't the case. @negroscuro can you please check and verify that?

**Comment by therter** [comment]
> @therter's import script would've have included Riga in our [Cities/Region](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/cities_regions/overview) taxonomy if it had all required input data/layers available. But I'm guessing for Riga this just wasn't the case.

Yes, Riga is not included in the [cities shape](http://services.clarity-h2020.eu:8080/geoserver/clarity/wfs?request=GetFeature&typeNames=clarity:mortality&outputFormat=SHAPE-ZIP)

**Comment by DenoBeno** [comment]
@humerh just told me that he has Riga in the database, written as "Rīga", code LV001C1.

This is a general issue - his recommendation is to switch to using codes if possible.

Another example: Liepāja, code LV002L1

**Comment by p-a-s-c-a-l** [comment]
> Yes, Riga is not included in the [cities shape](http://services.clarity-h2020.eu:8080/geoserver/clarity/wfs?request=GetFeature&typeNames=clarity:mortality&outputFormat=SHAPE-ZIP)

In which database? If it's not in the "cities shape" (@therter please provide a link to the respective layer), then there aren't all required local effects layer available, right @negroscuro ?

**Comment by therter** [comment]
> @therter please provide a link to the respective layer

The cities can be downloaded [here](http://services.clarity-h2020.eu:8080/geoserver/clarity/wfs?request=GetFeature&typeNames=clarity:mortality&outputFormat=SHAPE-ZIP)

**Comment by therter** [comment]
The name of the layer is clarity:mortality 

[preview of the mortality layer](http://services.clarity-h2020.eu:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Amortality&bbox=1995203.0178%2C1014243.9784%2C7079558.6386%2C5270223.5146&width=768&height=642&srs=EPSG%3A3035&format=application/openlayers)

**Comment by DenoBeno** [comment]
This layer indeed has no Riga in it. I opened it with Qgis and checked.

However, I know that @humerh  interpolates the mortality data for the cities where no mortality data is available. So now I'm confused - why would he need to do this if the city shapes are taken from the mortality layers.

**Comment by p-a-s-c-a-l** [comment]
> why would he need to do this if the city shapes are taken from the mortality layers.

Good Question. Maybe @negroscuro can answer that?

**Comment by negroscuro** [comment]
This happens because I only added cities mortality data for those which are available in the system in terms of UA, STL and ESM data sources.
Should I do it in a different way?


EDIT: I checked and there is data for Riga in UA2012, but not from STL. (both datasets comes arranged by city)
Regarding ESM not sure, I guess there should be data since it is raster data source for whole europe.

**Comment by DenoBeno** [comment]
UAL = urban atlas
STL = street tree layer
ESM = European settlement map

Mario Nuñez <notifications@github.com> schrieb am Mo., 3. Feb. 2020, 14:06:

**Comment by DenoBeno** [comment]
OK, The STL is a problem. No data for Riga.

Well, that does it then - we can't support Riga at the moment.

![image](https://user-images.githubusercontent.com/2961790/73933222-453f4200-48dc-11ea-9f5d-c44b8b0dd9d5.png)
