### ISSUE TITLE
Update CLARITY GeoServer URIs

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#66]
Once the [Export of Geoserver layers from MTG to ATOS](https://github.com/clarity-h2020/ckan/issues/23) has been completed. We have to update all GeoServer URIs of respective [resources](https://csis.myclimateservice.eu/admin/content?title=&type=data_package_metadata&status=All&langcode=All). AFAIK @therter knows how to do it directly on the level of the database.

Furthermore, I've noticed that there a two ATOS GeoServer instances:

- http://services.clarity-h2020.eu:8080/
- https://geoserver.myclimateservice.eu/

http://services.clarity-h2020.eu:8080/ still seems to cause problems with [include in report functionality](https://github.com/clarity-h2020/csis-helpers-module/issues/9#issuecomment-603831377),  since TLS is [not enabled](https://github.com/clarity-h2020/csis/issues/120#issuecomment-603774614) for services.clarity-h2020.eu.

**Question:** Will we move everything to geoserver.myclimateservice.eu? If not, https has to be supported for services.clarity-h2020.eu.

**Comment by negroscuro** [comment]
We plan to move to the new instance so probably it does not worth the effort to secure the old one.

**Comment by p-a-s-c-a-l** [comment]
What is now the correct instance for **all** layers (hazard + hazard-le input layers)? https://geoserver.myclimateservice.eu/ ?

We have to make the changes in the data packages before we set up the [synchronisation](https://github.com/clarity-h2020/csis/issues/135#issuecomment-617103328) between DEV and PROD instance of CSIS and also in EMIKAT which [currently](https://github.com/clarity-h2020/csis-technical-validation/issues/28) calls http://services.clarity-h2020.eu:8080

**Comment by p-a-s-c-a-l** [comment]
Question to @DanielRodera & @maesbri 

> What is now the correct instance for **all** layers (hazard + hazard-le input layers)? https://geoserver.myclimateservice.eu/ ?

@therter can prepare the update statements

**Comment by therter** [comment]
> @therter can prepare the update statements

The following update statements will adjust the geoserver urls, if only the url base must be changed.

```sql
update node__field_reference_path set field_reference_path_value = replace(field_reference_path_value, 'https://clarity.meteogrid.com/', 'https://geoserver.myclimateservice.eu/') where position('https://clarity.meteogrid.com/' in field_reference_path_value) = 1;
update node__field_reference_path set field_reference_path_value = replace(field_reference_path_value, 'http://services.clarity-h2020.eu:8080/', 'https://geoserver.myclimateservice.eu/') where position('http://services.clarity-h2020.eu:8080/' in field_reference_path_value) = 1;

```

**Comment by p-a-s-c-a-l** [comment]
@therter this is done, right? 
Did you also check for other services.clarity-2020.eu appearances?

**Comment by therter** [comment]
> @therter this is done, right?

Yes, this is done and on the [maintenance](https://csis-dev.myclimateservice.eu/maintenance) site, the url was also corrected.
