### ISSUE TITLE
New geoserver (geoserver.myclimateservice.eu) uses different layer names

### ISSUE THREAD

**Issue by therter** [clarity-h2020/data-package#67]
@ghilbrae @DanielRodera The new geoserver uses an other naming convention for the layer names (not the title). It uses a underscore instead of a minus between dates. 

For example the layer europe:CI_frost-days_rcp85_20110101-20401231_ensmean  has now the name europe:CI_frost_days_rcp85_20110101_20401231_ensmean

This should be corrected, because the names will be automatically built by the mapping component and will use the minus instead of the underscore.

**Comment by ghilbrae** [comment]
We'll have to look into it but it seems it is something geoserver has done on its own. We used an import module within geoserver and it seems it might have changed that for whatever reason. 
What do you think @DanielRodera any insights into this?

**Comment by p-a-s-c-a-l** [comment]
@therter Is this at least consistent across all layers? Can you check if the layer names are actually used in data packages? With the introduction of template resources, the time period part of the URLs *should* have been replaced by $time_period in all URLs.  In this case we could simply change the [variables](https://csis.myclimateservice.eu/taxonomy/term/5697). 

However, this does not apply to URLs referenced in CKAN. Here we have to update them manually. 

@DanielRodera Any time estimate on when this would be addressed on your side?
How is this layer information stored in GeoServer? XML config? Database? Could it be handled by a simple search and replace?

**Comment by therter** [comment]
> Is this at least consistent across all layers?

Yes, it is.

> Can you check if the layer names are actually used in data packages?

At least in the Naples data package are the layer names used. But I can use update statements to change the layer names in the database. That shouldn't be much effort.

**Comment by DanielRodera** [comment]
Hi guys, 

We are looking into this to find out is there is a way to change all the names quickly. 

If we have to change all the names by hand I am afraid it will take too much time,

I will keep you updated,

**Comment by p-a-s-c-a-l** [comment]
@humerh @DenoBeno @patrickkaleta Does this have any influence on EMIKAT?

**Comment by humerh** [comment]
The link https://geoserver.myclimateservice.eu/geoserver is not reachable. What is the new address??

**Comment by DanielRodera** [comment]
Hi Heinrich, 

We stopped the Geoserver for a moment to make a backup, should be reachable again, 

Sorry for the inconveniences

**Comment by DanielRodera** [comment]
Hi everyone,

We have changed the names of all layers to the name they should have,

@therter, could you please try again?

If you find any problem please let me know,

**Comment by therter** [comment]
> @therter, could you please try again?

Thanks, it works

**Comment by humerh** [comment]
Sorry, I have problem with the new geoserver.
My internal call to the geoserver is this:
https://geoserver.myclimateservice.eu/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity%3Aland_use_grid&maxFeatures=100000&bbox=16.317125%2C48.250858%2C16.51531%2C48.290538%2CEPSG:4326&outputFormat=SHAPE-ZIP

I get the error message: 

" Illegal property name: for feature type clarity:land_use_grid "


I suppose, that the outputFormat=SHAPE-ZIP  is not supported.

**Comment by p-a-s-c-a-l** [comment]
@therter perhaps you can have a look and enable SHP download?

**Comment by DanielRodera** [comment]
Hi @humerh, is solved,

If you have any other request let me know,

**Comment by p-a-s-c-a-l** [comment]
Thanks
