### ISSUE TITLE
The legends of the wind indices are all displayed with units "days"

### ISSUE THREAD

**Issue by therter** [clarity-h2020/data-package#70]
The legends of the wind indices are all displayed with units "days", even though only for the torro17 index the units are days, for the rest the units should be m/s

This should be changed in the WMS style.

**Comment by DanielRodera** [comment]
Hi, the styles have been created by MTG people, I assigned @ghilbrae. I will keep in the issue if you need support in the Geoserver configuration.

**Comment by p-a-s-c-a-l** [comment]
Any updates on this issue @therter ?

**Comment by p-a-s-c-a-l** [comment]
> Any updates on this issue @therter ?

**Comment by ghilbrae** [comment]
@therter I've changed the units for WI_98perc_sfcWindmax_XXXX and WI_FXx_XXXXX layers. It should now show m/s units.

Let me know if it's missing somewhere else.
