### ISSUE TITLE
The geoserver delivers a wrong map image

### ISSUE THREAD

**Issue by therter** [clarity-h2020/data-package#72]
The geoserver delivers sometimes a wrong map image. 

Example: if you send a GetMap request for the layer [europe:HI_tropical-nights_historical_19710101-20001231_ensstd](https://geoserver.myclimateservice.eu/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3AHI_tropical-nights_historical_19710101-20001231_ensstd&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619), then sometimes, you will get the correct image and sometimes you will get a wrong image. 

I get the follwing results for the same map (I only pressed F5 to reload the page)

![Bildschirmfoto vom 2020-06-22 12-22-39](https://user-images.githubusercontent.com/1788509/85277421-b0507600-b483-11ea-9108-81c883a0cebe.png)
   
![Bildschirmfoto vom 2020-06-22 12-22-54](https://user-images.githubusercontent.com/1788509/85277435-b47c9380-b483-11ea-9647-e4a84248c032.png)

![Bildschirmfoto vom 2020-06-22 12-23-00](https://user-images.githubusercontent.com/1788509/85277444-b6465700-b483-11ea-9aa2-2b814727886b.png)

**Comment by p-a-s-c-a-l** [comment]
Same problem encountered here: https://github.com/clarity-h2020/csis-technical-validation/issues/54#issuecomment-647943112

I'm also able to reproduce the problem. Layer data source is a GeoTIFF, right? Did this also happen on METEOGRID GeoServer? @therter can you please check it out?

**Comment by therter** [comment]
> Did this also happen on METEOGRID GeoServer?

This did not happen on the [meteogrid geoserver](https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3AHI_tropical-nights_historical_19710101-20001231_ensstd&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619)

**Comment by p-a-s-c-a-l** [comment]
Does this error occur only with this particular layer or also with other layers?
The source of the layer is this file: `file:geoserver_MTG_18032020/data/new/heat/tropical-nights/HI_tropical-nights_historical_19710101-20001231_ensstd.tif`. Perhaps it got corrupted? I cannot access the original file, so I cannot check that.

@DanielRodera Could you please download and verify `HI_tropical-nights_historical_19710101-20001231_ensstd.tif` and if required replace it with the original one from METEOGRID geoserver?

**Comment by p-a-s-c-a-l** [comment]
@DanielRodera @ghilbrae 

Can please check whether the [advanced layer properties](https://geoserver.myclimateservice.eu/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.resource.ResourceConfigurationPage?7&name=HI_tropical-nights_historical_19710101-20001231_ensstd&wsName=europe) on METEOGRID and ATOS Geo server are exactly the same? I don't have access to METEOGRID server, so I cannot have a look.
The following layer properties look suspicious:

**keep native** 

![image](https://user-images.githubusercontent.com/1788226/85396068-633ad580-b551-11ea-8d38-a37139ee06aa.png)

**Rescale Pixels** (btw, I'm not able to change this)
![image](https://user-images.githubusercontent.com/1788226/85396157-8796b200-b551-11ea-883b-2804bc7e420c.png)

**Comment by therter** [comment]
> Does this error occur only with this particular layer or also with other layers?

This error occurs also on other layers (for example [this](https://geoserver.myclimateservice.eu/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3ACI_Tn10p_rcp26_20410101-20701231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619), [this](https://geoserver.myclimateservice.eu/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3ACI_frost-days_rcp85_20410101-20701231_ensstd&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619) and [this](https://geoserver.myclimateservice.eu/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3ADI_consecutive-dry-days_rcp26_20710101-21001231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1800244.8901724715,6066042.564711587,1917652.1656185023,6183449.840157619)). But it seems that the error only occurs on layers, which are using a tiff file as data source. The layers, which are using the postgis db as data source have no problems with wrong images (I have tested [basins](https://geoserver.myclimateservice.eu/geoserver/clarity/ows?&service=WMS&request=GetMap&layers=clarity%3Abasins&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1594782.1581419175,4980025.266835805,1624133.9770034251,5009377.085697314), [vegetation](https://geoserver.myclimateservice.eu/geoserver/clarity/ows?&service=WMS&request=GetMap&layers=clarity%3Avegetation&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1594782.1581419175,4980025.266835805,1624133.9770034251,5009377.085697314) and [trees](https://geoserver.myclimateservice.eu/geoserver/clarity/ows?&service=WMS&request=GetMap&layers=clarity%3Atrees&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&tileSize=1536&attribution=&bbox=1594782.1581419175,4980025.266835805,1624133.9770034251,5009377.085697314)).

**Comment by ghilbrae** [comment]
@p-a-s-c-a-l if you still need to check in our server, I've set up a user for you to do so. I'll send you the credentials.

The properties for the layer europe:HI_tropical-nights_historical_19710101-20001231_ensmean, look like this in our geoserver:

![image](https://user-images.githubusercontent.com/1615745/85510447-9fc10c80-b5f7-11ea-9a3a-e4b1aa84a128.png)

**Comment by p-a-s-c-a-l** [comment]
@DanielRodera Did you compare the 2 tif files?

**Comment by DanielRodera** [comment]
Hi @p-a-s-c-a-l,

The tiffs are the ones MTG provides to us. I cannot compare them because I have no access to the original files,

The configuration is the same as the Ángela´s screenshot. I am afraid I cannot help much more. 

@ghilbrae, the tiffs you provided are stored in the ATOS FTP, could you please check if there are the same as the original ones you have in your GeoServer??

**Comment by p-a-s-c-a-l** [comment]
I've disabled JAI Tile Recycling and the error *seems* to be gone.

![image](https://user-images.githubusercontent.com/1788226/85713067-46390a80-b6e9-11ea-965d-c6be9411aae0.png)

@DanielRodera / @therter Can you please check with other layers if this really solved the problem? 

Tile Recycling allows JAI to re-use already loaded tiles, which can provide significant performance improvement. So disabling it is not a good idea. ~~So @DanielRodera you could check the JVM settings and check if **native JAI** can be enabled or has to be [installed](https://geoserver.geo-solutions.it/edu/en/install_run/jai_io_install.html). This might require patching the GeoServer Docker image, but that's not a big deal. we did the same with Drupal.~~ (native JAI has no support for NODATA pixels, so we probably can't use it).

**Comment by therter** [comment]
> Can you please check with other layers if this really solved the problem?

I can no longer reproduce the problem. It seems to be fixed.

**Comment by ghilbrae** [comment]
> @ghilbrae, the tiffs you provided are stored in the ATOS FTP, could you please check if there are the same as the original ones you have in your GeoServer??

@DanielRodera  Yes, they are the same. I took all the files directly from the data directory on our geoserver.

**Comment by p-a-s-c-a-l** [comment]
> I can no longer reproduce the problem. It seems to be fixed.

OK.

**Comment by vuvkar** [comment]
Hi everyone, I have the same problem over my dataset. Were you able to fix the issue?
I have tile recycling disabled :/
