### ISSUE TITLE
The Urban Atlas 2012 background layers do not work 

### ISSUE THREAD

**Issue by therter** [clarity-h2020/data-package#74]
The Urban Atlas 2012 layers are not working in the [map](https://csis.myclimateservice.eu/study/35/step/1530/view/maps)

- [Urban Atlas 2012](https://image.discomap.eea.europa.eu/arcgis/services/UrbanAtlas/UA_UrbanAtlas_2012/MapServer/WmsServer?&service=WMS&request=GetMap&layers=%24%7Blayer%7D&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=2622095.8182946863,4569099.802774697,2651447.637156194,4598451.621636205): the [path](https://csis-dev.myclimateservice.eu/node/2039) uses a variable that is not replaced.
- [Urban Atlas 2012 [Building Height]](https://image.discomap.eea.europa.eu/arcgis/services/UrbanAtlas/UA_BuildingHeight_2012/MapServer/WmsServer?&service=WMS&request=GetMap&layers=0&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=2622095.8182946863,4569099.802774697,2651447.637156194,4598451.621636205): the [path](https://csis-dev.myclimateservice.eu/node/2048) returns a "404 Not Found" response

**Comment by p-a-s-c-a-l** [comment]
Can you please post also a link the the **resource**?

**Comment by therter** [comment]
> Can you please post also a link the the **resource**?

Link to the resource [Urban Atlas 2012](https://csis-dev.myclimateservice.eu/node/2040)
Link to the resource [Urban Atlas 2012 [Building Height]](https://csis-dev.myclimateservice.eu/node/2049)

**Comment by p-a-s-c-a-l** [comment]
The layers are no longer available online, I've removed them from the data packages.
