### ISSUE TITLE
Update availability of HC-LE data

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/data-package#75]
We've recently synchronised DEV ->PROD CSIS and updated the list of supported cities from the information retrieved from geoserver.myclimateservice.eu. This is the current situation regarding availability of cities HC-LE input data for screening:

![image](https://user-images.githubusercontent.com/1788226/86924839-4943ea00-c130-11ea-8bd4-851d39e411db.png)

As @DenoBeno mentioned, we've to urgently update the information on data availability for [heat wave local effect and pluvial flooding local effect](https://geoserver.myclimateservice.eu/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Acity&bbox=1969465.0%2C996016.875%2C7168551.0%2C4677889.0&width=768&height=543&srs=EPSG%3A3035&styles=hw_availability&format=text%2Fhtml%3B%20subtype%3Dopenlayers#toggle) ("cities layer").

Moreover, we don't have to forget to [publish Hazard Local Effects Input Layers as OpenData](https://github.com/clarity-h2020/ckan/issues/31) as we've announced in the **Data Management Plan**. But this can only be done when all layers have been loaded. Can you give an estimate when this is expected to be completed @DanielRodera ?

**Comment by DanielRodera** [comment]
Hi @p-a-s-c-a-l ,

The status: 

We noticed there were about 20 cities with missing layers and we fix the scripts and reload them all in a new DDBB.

The DDBB with the new data is already loaded in our server, we will update in the Geoserver today on EOB time.

We also created a script which loads all the cities which have the data requirements for been calculated. This step is needed for the following steps.

We are preparing another VM to parallelize the process to load the cities faster. We also prepared a new database empty with only the data needed for running all the scripts in differents VM at the same time. 

AIT offered a VM for running the scripts as well, we put a copy of our VM in the Atos FTP server. Once the VM is up and running we will have 3 different VM loading data at the same time. It will speed up the loading process very much.

**Comment by DenoBeno** [comment]
I have asked for the server at AIT. Please:

1) remind me on the specs for the server
2) Explain how to start the scripts once we have a server.

thx
 Denis

**Comment by DanielRodera** [comment]
Hi @DenoBeno,

The server requirements are the following:
RAM: 48Gb
Cores: 8
Disk Space: About 140 Gb (the VM backup is around 100Gb)

In order to run, you will need to install Xeon virtual management software.

As @maesbri said in the mail, would be nice if we could have access to the server to run the scripts and make the proper setup. If it is not possible, I will send you a detailed guide on how to run all the processes by mail.

**Comment by p-a-s-c-a-l** [comment]
> The DDBB with the new data is already loaded in our server, we will update in the Geoserver today on EOB time.

Did you update the Geoserver DB @DanielRodera ? This is the current status. It doesn't look different than [this one](https://github.com/clarity-h2020/data-package/issues/75#issue-653305745):

![image](https://user-images.githubusercontent.com/1788226/87778011-ceaf5480-c82a-11ea-9cd4-83f98ffecca7.png)

**Comment by p-a-s-c-a-l** [comment]
> Did you update the Geoserver DB @DanielRodera ? This is the current status. It doesn't look different than [this one](https://github.com/clarity-h2020/data-package/issues/75#issue-653305745):

**Comment by DanielRodera** [comment]
Hi,

I updated the database, now there are 192 cities available:

![image](https://user-images.githubusercontent.com/42216407/88536949-ecd83a00-d00c-11ea-9201-b04952ed14f7.png)


Let me know if you find any error, we have a backup to go back to the original database if needed,

**Comment by patrickkaleta** [comment]
Shall I (or @therter) now run the [republish script ](https://github.com/clarity-h2020/docker-drupal/blob/dev/scripts/republish.sh) on DEV and check how many cities will be available there?

**Comment by therter** [comment]
> Shall I (or @therter) now run the [republish script ](https://github.com/clarity-h2020/docker-drupal/blob/dev/scripts/republish.sh) on DEV and check how many cities will be available there?

Yes, you can start the script, so that we can check, if emikat can do calculations for the new cities.

**Comment by patrickkaleta** [comment]
> > Shall I (or @therter) now run the [republish script ](https://github.com/clarity-h2020/docker-drupal/blob/dev/scripts/republish.sh) on DEV and check how many cities will be available there?
> 
> Yes, you can start the script, so that we can check, if emikat can do calculations for the new cities.

Tried to execute the script on DEV, but it fails with error: `bash: /usr/bin/shp2pgsql: No such file or directory`

Script on DEV seems to be the same as the most recent version of it in the [Git repo](https://github.com/clarity-h2020/docker-drupal/blob/dev/scripts/republish.sh) (2 months old). Is there maybe a newer version of the script somewhere or do I need to run anything else before running the republish script?

**Comment by therter** [comment]
> Tried to execute the script on DEV, but it fails with error: `bash: /usr/bin/shp2pgsql: No such file or directory`
> 
> Script on DEV seems to be the same as the most recent version of it in the [Git repo](https://github.com/clarity-h2020/docker-drupal/blob/dev/scripts/republish.sh) (2 months old). Is there maybe a newer version of the script somewhere or do I need to run anything else before running the republish script?

This is the newest version. It seems that shp2pgsql is not installed within the postgis docker container since the last image update. I will take a look at it.

**Comment by therter** [comment]
The new cities are now in the dev instance.

There were two problems after the last image update:

#### The drupal database was not updated and tried to use the postgis-2.5.so library.

Normally, this can be fixed with the following command (see [here](https://github.com/postgis/docker-postgis#known-issues--errors))

```
docker exec csis-postgis update-postgis.sh
```

But in this case, the update-postgis.sh script also tried to use the old library, so within the postgis container, a symbolic link to the existing postgis-3.so library had to be created.

```
/usr/lib/postgresql/10/lib# ln -s postgis-3.so postgis-2.5.so 
```

#### The tool shp2pgsql was not installed

The new docker image does not install the postgis client tools. So I had to install the postgis client tools with the following commands:

```
apt-get update
apt-get install postgis
```

After this, it was possible to execute the republish script

**Comment by p-a-s-c-a-l** [comment]
> The new cities are now in the dev instance.
> 
> There were two problems after the last image update:
> #### The drupal database was not updated and tried to use the postgis-2.5.so library.
> 
> Normally, this can be fixed with the following command (see [here](https://github.com/postgis/docker-postgis#known-issues--errors))
> 
> ```
> docker exec csis-postgis update-postgis.sh
> ```
> 
> But in this case, the update-postgis.sh script also tried to use the old library, so within the postgis container, a symbolic link to the existing postgis-3.so library had to be created.
> 
> ```
> /usr/lib/postgresql/10/lib# ln -s postgis-3.so postgis-2.5.so 
> ```
> 
> #### The tool shp2pgsql was not installed
> 
> The new docker image does not install the postgis client tools. So I had to install the postgis client tools with the following commands:
> 
> ```
> apt-get update
> apt-get install postgis
> ```
> 
> After this, it was possible to execute the republish script

@therter When we recreate the container, [your customisations](https://github.com/clarity-h2020/data-package/issues/75#issuecomment-666417615) are lost. Therefore we have to create a custom `postgis/postgis:10-3.0` image as we did for [Drupal](https://github.com/clarity-h2020/docker-drupal/tree/dev/drupal).

**Comment by p-a-s-c-a-l** [comment]
> The new cities are now in the dev instance.
> 
> There were two problems after the last image update:
> #### The drupal database was not updated and tried to use the postgis-2.5.so library.
> 
> Normally, this can be fixed with the following command (see [here](https://github.com/postgis/docker-postgis#known-issues--errors))
> 
> ```
> docker exec csis-postgis update-postgis.sh
> ```
> 
> But in this case, the update-postgis.sh script also tried to use the old library, so within the postgis container, a symbolic link to the existing postgis-3.so library had to be created.
> 
> ```
> /usr/lib/postgresql/10/lib# ln -s postgis-3.so postgis-2.5.so 
> ```
> 
> #### The tool shp2pgsql was not installed
> 
> The new docker image does not install the postgis client tools. So I had to install the postgis client tools with the following commands:
> 
> ```
> apt-get update
> apt-get install postgis
> ```
> 
> After this, it was possible to execute the republish script

**Comment by p-a-s-c-a-l** [comment]
@DenoBeno Please keep in mind that once the calculation is finished, somebody has to update the respective open data sets we've [uploaded to Zenodo](https://zenodo.org/communities/clarity/search?page=1&size=20&q=local-effects&keywords=Local%20Effects&file_type=zip&access_right=open). See [Publish Hazard Local Effects Input Layers as OpenData](https://github.com/clarity-h2020/ckan/issues/31).

I tried to make an intermediate update of the datasets today, but I [was not able](https://github.com/clarity-h2020/ckan/issues/31#issuecomment-672688570) to download the SHP files from `geoserver.myclimateservice.eu`. So this has to be fixed first or the local effects input data has to be uploaded to the CLARITY sFTP.

Furthermore, the Local Effects Datasets GeoServer URIs [have to be updated](https://github.com/clarity-h2020/ckan/issues/35) in CKAN.
