### ISSUE TITLE
Clone Data Package for European Transport

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/data-package#78]
Hi! We are going to create the European Data Package for transport and we want to start from the European Wide Data Package (https://csis.myclimateservice.eu/node/682) because there are more than a few resources there that we will need too.

We've spoken with @DanielRodera and he has pointed out that there are two options: having admin permissions or having someone clone it for us. I think the second option is best and then having it owned by users meteogrid and angela. 

I suppose that it will be created in DEV first. Do we have to wait for the synchronization to PROD to have it there or can it be created there too once we all see that it works?

Thanks!!

**Comment by patrickkaleta** [comment]
Yes, the data package should be created in DEV and once it's finished it can be synchronized to PROD. Creating it on PROD a second time is not a solution, since after the next sync process this data package would then be on PROD twice.

**Comment by luis-meteogrid** [comment]
Hi @patrickkaleta, could you clone the datapackage and assign it to angela or/and meteogrid so we can use it for European transport studies?.

**Comment by patrickkaleta** [comment]
> Hi @patrickkaleta, could you clone the datapackage and assign it to angela or/and meteogrid so we can use it for European transport studies?.

I've cloned the European Wide DP on [DEV](https://csis-dev.myclimateservice.eu/node/5580) and made @ghilbrae the author of it. Please keep this [comment ](https://github.com/clarity-h2020/csis/issues/156#issuecomment-609766874)by Pascal in mind when working with the cloned DP.

**Comment by luis-meteogrid** [comment]
Thank you @patrickkaleta , I have already seen the new Data-package for transport. Just a thing before we start working with it. May we remove contents from the data-package? Let say the Adaptation-options
![image](https://user-images.githubusercontent.com/1586268/91864270-4d900d80-ec70-11ea-91d6-7545d68636d7.png)
I suppose that if we press the remove button we simply unlink  the data-package from the new data-package but we are not deleting the content neither unlinking it from the original one, it is that true?

**Comment by patrickkaleta** [comment]
> I suppose that if we press the remove button we simply unlink the data-package from the new data-package but we are not deleting the content neither unlinking it from the original one, it is that true?

**Correct!** After clicking the "Remove" button the system shows a second checkbox asking whether you also want to remove the item completely from the system, but AFAIK your users don't have the permission to even see this additional dialog, so you cannot completely remove the items.

You only need to be careful with the available "Edit" button, since changing the item would then also be affecting the same item in the original data package (as explained in this [comment](https://github.com/clarity-h2020/csis/issues/156#issuecomment-609766874) by Pascal).

**Comment by luis-meteogrid** [comment]
Thank you again @patrickkaleta
